label a2s1:
"..."
unk "\"Understand that this will not be easy, even for the parents.\""
unk "\"The pain will be temporary.\""
"What's happening?"
"..."
unk "\"You will know in time...but not yet.\""
scene bg black with slow_dissolve
"Time loses meaning."
"Blackness...simultaneously eternal and non-existent."
"Nightmares ebb and flow, building and fading."
"Scenes from my earliest childhood to my landing on Adastra, all warped by horrific and violent imagery that never happened."
"But as soon as each one ends, I forget, just like any other dream...except one."
scene bg spaceship with slow_dissolve
play background "sfx/spaceshipinterior.ogg" fadein 3.0
"I'm huddled in the seat of the ship, freezing cold, numb with desperation and the fear of impending death."
"How is this happening to me?"
"What did I do to deserve this?"
"I glance back at the crumpled form of the wolf in the back of the ship."
"His head is framed by a pool of blood, the metal pipe just a few feet away where I'd dropped it."
"I've made a huge mistake."
"The anger and terror I'd been feeling over the past several hours, days—"
"...weeks?"
"—builds until I scream and smash both of my fists on the glowing panels in front of me."
play sound "sfx/firestart.ogg"
play background "sfx/starrumble.ogg"
scene bg spaceshipstar at my_shake with dissolve
"The next thing I know, light blasts the interior of the ship and I cover my face with my hands."
"Still, the light pierces through and I see blood-red."
"The ship vibrates violently, and I know right away that we're being pulled into it."
"I reach out despite the impossible light, uselessly pounding at the unresponsive panels."
"After a few moments, the brightness and heat become unbearable, and I finally throw myself to the floor, crawling away, crawling toward my wolf."
m "\"Amicus, HELP!\""
scene bg white with slow_dissolve
stop background fadeout 5.0
"But the light continues to grow, and soon everything is lit up in a blinding white, the heat so intense that the metal melts underneath my hands and knees."
"I'm on fire...I {i}am{/i} fire. I feel lines of molten lead course through from the base of my neck, down my spine, branching out into my limbs, even my toes and fingers."
"I can only float in the inferno, dumbly wondering why I still feel if I'm dead, wondering if this {i}is{/i} death as the ship, the wolf, and I become part of the star."
"Once again, time is lost and I only exist as fire."

scene bg islandnight with slow_dissolve
play loop "sfx/lakesounds.ogg" fadein 5.0
"I stare up at the sky, the air suddenly cool as I try to comprehend the sudden change from the harsh, all-consuming starlight, to the gentle, cold moonlight."
"Still, fire continues to lance through my head, neck, spine, and limbs in agonizing lines, my body mapped as a tortured stick figure."
"It hurts...hurts more than anything I've ever experienced, but it's fading after what happened in the star, so I try to relax in the sand."
"After a few minutes, I realize that I can hear the waves, and I feel something drawing me toward the water."
"I'm a little scared of getting up, of any movement at all, terrified that it might trigger the pain anew...but it doesn't."
"It almost feels like I'm not moving at all."
scene bg lakenight with dissolve
"I glide toward the water, watching the surface reflect the bright planet and moon in hypnotic ripples."
"Entering the lake and feeling the cold, gentle water wash over my skin is the best feeling I've ever felt."
"It envelops me slowly, moving up my legs, torso, and finally my head, and just like that, the pain and fire is chased away, subdued to a dull, tingly throb."
"I gasp in relief, somehow able to breathe under the water."
"I drift through the dark water, watching the globes of light dance and sway above me before I finally resurface."
"It's only then that I remember Amicus."
"Fear grips me."
"Was he still on that ship?"
"Did I leave him behind in the star?"
"I look up and see the lights glittering from the palace and I begin to swim towards it, somehow moving much faster than I should be able to."
"Instead of swimming to the beach though, I end up moving toward the balcony, straight to Amicus's room."
"As I get closer, I realize that someone IS on the balcony."
"It's Amicus, and my heart fills with relief."
"He's got his back to the railing, leaning against it casually."
"Even though I can only see him from behind, I realize that it's not the Amicus I know."
"Instead, he's in full robes, and he's a lot more skinny than I remember."
"I slow down, wondering why he's not looking at me with all the splashing noises I'm making."
"Just as I'm about to call up to him though, I see brown arms wrap around him, smoothing over his arms and back and that's when Amicus turns to the side."
"I see now that those arms belong to another wolf, smaller and brown-furred, one that I've never seen before."
"Amicus is doing the same to him, paws moving around his body in a way that's awkward and hesitant...a pair of young lovers making out for the first time."
"I watch, suddenly feeling embarrassed."

scene bg amicusroom with dissolve
stop loop
"I'm back in Amicus's room, and that same, teen-aged wolf is now on the sofa, bent over, hiding his face behind his paws."
"I've never seen Amicus really cry, but I can tell that's what he's doing now."
"I feel the sense of complete and utter shame, the feeling that you've let everyone down."
"It consumes me."
"I reach out toward the young wolf, wanting to comfort him, wondering if he'll even know who I am."

scene bg space with dissolve
"Suddenly, I'm sucked back into the cosmos."
"There is no parent this time."
"Instead, I float peacefully through the vacuum, staring down at what I assume is Adastra."
"Even though there isn't anyone here with me, I sense beings all around me."
stop music fadeout 10.0
"I also get a sense of approval, like their work is done."
"\"Finish Meera's work, young human...\""
"Just like that, I start to drift back down toward the moon, descending faster and faster until everything becomes a blur."

scene bg garden2night with transition_fade
play loop "sfx/crickets.ogg" fadein 3.0
"This time, coming to feels real, and I immediately know I'm not in a dream."
"I smell lavender."
"Amicus?"
"My eyes feel like they're glued shut and I have to rub at them to get them to fully open."
"The first thing I see is the sky, the planet {i}Ancoris{/i}, and the moon {i}Torque{/i}, both of them glowing brightly."
"I stare at the two floating orbs for a while, waiting for things to fall into place as to why I'm out here."
"I'm laying on something hard, like concrete, and I feel soft, but weighty things on my chest."
"My hands are curled around it, and I lift it slowly to have a look, even though it feels like a 50 pound dumbbell."
"Flowers..."
"Flowers with a fair bit of lavender mixed in."
"Slowly, I turn my head and again, I get the feeling of heavy weights attached to my body."
"I somehow manage it and immediately see that I'm in the amphitheater."
"At the same time, I see more flowers and I realize that they're arranged all around me in a circle."
"Moving my head around also makes me realize that there's something scratchy and prickly on my head."
"Still struggling with my heavy hand, I reach up and grab at it."
"I lift it from my head and hold it in front of my face, my eyes taking a few moments to focus to find out that it's a wreath, pink flowers woven into the twigs."
"I finally drop my arm to the side, getting too tired to hold it up and I watch it lazily roll a few feet away."
"The movement sends a wave of tingling through my body, but it fades quickly"
"The heavy weakness is also starting to fade, but I'm more worried about how I got here, and why I'm covered in flowers."
"From what I can tell, I'm in the gardens, though a part of it I haven't been to before."
"I close my eyes, trying to remember how I got here."
"Amicus...the Trial of Rhetoric...the restaurant...being sick."
"Again, I lift my arm, though it's easier this time, and I look at the skin."
"It's covered in crusty, yellow-ish scabs, though they don't hurt."
"I don't know why, but I get the feeling that the skin underneath is completely healed."
"I try to think again."
"I do remember throwing up on Cassius, but after that...just terrible dreams."
"Did they heal me somehow?"
"Is this flower thing part of that?"
"I'm feeling some of my strength returning, so I force myself into a sitting position, joints popping and muscles stiff."
"Still, with every movement things get easier."
"I do get light-headed though, and I have to sit there for a moment, looking around again, wondering where Amicus is."
"He'd sounded so desperate and sad the last I heard him."
"I need to show him that I'm okay now...at least I think I am."
"I slowly push myself up, listening to the gunshot cracks of my knees, as if I hadn't used them for days."
"I stand unsteadily in the center of the square, looking around at the circle of flowers."
"I'm startled when I turn and see a wolf behind me...but it's just a sculpture."
"A male wolf decked out in armor, both of his paws raised to the sky."
"He's got a bunch of flowers weaved around his wrists and on his head too."
"I wait a few moments, listening for anyone that might be nearby."
"All I hear are the insects around me."
"So, I start to move toward the path that I know leads to the palace."
"Although I'm pretty sure I'm not dreaming now, this eerie scenario has me questioning that."
"The whole situation is surreal."
"All of the things that I remember happening last feel so distant."
"Despite spending all of my time on Adastra trying to be covert, I find myself longing to find someone, anyone really."
"I just need to know what's happened."
"And pretty soon, I do find someone."
"His back is to me, stooped over, fur almost ghostly in the glow of the garden lights."
"The cat busies himself with some flowers, a pair of metal clippers in his paws."
"As I get closer, I can hear him humming just above the noise of his busy snipping."
"I'm just opening my mouth when I see his ears perk."
al "\"Cass? You know I don't like these games.\""
show ale with dissolve
"Alex turns to face me, a knowing smile on his lips."
show ale shocked with dis
"That quickly disappears the second he sees me though, replaced by a look of complete shock."
al "\"Ah—\""
"Whatever he was trying to say doesn't seem to want to come out, and instead, he just stands there, gaping at me."
m "\"H—hey...\""
"I can barely talk, my voice rasping out like sandpaper on wood."
"I take a step forward and that's when Alex finally reacts, jumping almost a foot into the air in a backwards motion, putting space between us as he yelps."
show ale vshocked e at jumping with dis 
al "\"What...what!? How!?\""
"He stutters, and stumbles over his words."
"I've seen Alex flustered before, but never like this."
"There's real fear in his eyes as he stumbles against some bushes."
"I wonder if he's just going to take off running, but instead he stands there, quivering as he holds the clippers up in front of his chest, as if contemplating using them as a weapon."
"I raise my hands reassuringly."
m "\"Hey...Alex, it's me...\""
"I cough a few times, trying to clear my throat."
"I see Alex's ears twitch at the sound as he slowly lowers the clippers, though he moves to the side away from the bush, giving himself a clear path to the palace."
show ale shocked e with dis
al "\"[mc]? But how?\""
"He's staring at me like what he's seeing is impossible."
m "\"How what?\""
"I'm regaining my voice slowly, but surely."
m "\"What's happening?\""
"Alex finally seems to get a hold of himself, fur slowly laying flat again as he eyes me, looking almost suspicious."
show ale serious with dis
al "\"I could ask you the same thing.\""
"This catches me off-guard."
m "\"Why?\""
al "\"Well...\""
"Alex looks around before focusing on me again, tilting his head, as if to look at me from a different angle."
show ale tilt with dis
al "\"You were...you were dead.\""
m "\"Dead?\""
al "\"Well, not completely, but you were in a coma that we were told you would not wake up from.\""
m "\"Oh.\""
"I look down at myself, as if to confirm that I am indeed alive and well."
"Aside from the patchy scabs all over my arms and legs, I feel okay, aside from the grogginess."
m "\"I thought the doctor healed me.\""
"Alex's ears perk."
show ale shocked with dis
al "\"Doctor?\""
m "\"I mean, I think there was a doctor...I heard him when I was brought back here.\""
show ale serious with dis
"Alex's eyes narrow."
al "\"Amicus told us you were vegetative before he arrived, how did you hear him?\""
m "\"I...I dunno, I might have dreamed it. I was really out of it.\""
al "\"If you were still concious when he arrived, he should have been able to halt the damage caused by the virus. Who was the doctor?\""
"With every passing second, I regain more and more of my wits, and Alex's demeanor is confusing me."
"He thought I was dead, and instead of being happy, I feel like he's interrogating me."
"That's also when I realize something else:"
m "\"Wait, you all think I'm dead?\""
show ale tilt w with dis
al "\"Well, not me anymore, obviously. This is all very strange...how did you survive, exactly?\""
"Now the cat is starting to annoy me, and I look past him toward the palace, the situation finally dawning on me."
m "\"Where's Amicus?\""
"The cat is quiet for a moment, as if contemplating something, then quirks his head."
al "\"I'm not sure. He's been here and there, though I haven't seen him for at least a day.\""
"I walk past the cat, toward the palace, realizing what sort of state the wolf might be in."
show ale with dis
al "\"Where are you going? I'm very happy to see that you are well. This is all just very sudden and unexpected.\""
"I ignore Alex, not really in the mood to figure out why he's acting the way he is."
"He's making me feel like I'm still dreaming."
hide ale with dissolve
"So I walk quickly, and I'm relieved that he doesn't follow me."

scene bg palace1night with dissolve
"The wave of cool air that hits me as I enter the palace is a welcome feeling, and I find myself grateful to be back."
"Despite having apparently been here the whole time, it really does feel like I've been away for weeks."
"I pick up the pace as I head toward Amicus's room, practically jogging."
"I have to let him know that I'm okay."
"The short distance to his room seems like it takes longer than it ever has before, and I'm glad that I don't run into anyone else on the way."
"That interaction with Alex was weird and I don't need a repeat of that right now."
"I finally make it to his door and I immediately hear muffled chattering behind it."
"I don't hesitate though, and I press my hand to the panel."
play sound "sfx/dooropen.ogg"
stop loop fadeout 3.0
scene bg amicusroomdim with dissolve
"The door slides open, and instead of the usual blast of even colder air I would often get from Amicus's room, it's stuffy, warm, and the smell a little bit musky."
"The lights are dimmed, and my heart sinks when I see the empty bed."
"I linger in the doorway though, something feeling off."
"The droning chatter is Com, giving what sounds like a monologue on the history of some past emperor."
"I see wine bottles too, mostly bunched together on top of the bedside table, but there are also a few laying here and there on the floor."
m "\"Amicus?\""
"I call out, starting to become afraid of what I might find."
"I take a few tentative steps into the room, then I hear a loud snore and instantly, the worry gripping my chest starts to release."
"I'd recognize that sound anywhere."
"I hurry over to the other side of the bed where I find my wolf splayed out on the floor, a wine bottle next to his head, only in his underwear."
"He's clearly asleep...or passed out, muzzle hanging wide open as another, thunderous snore shakes the floor."
m "\"Amicus!\""
"I crouch down next to him, resting a hand on his chest, trying to shake him awake."
"His only response is a few more broken snorts before drooling out the side of his muzzle."
"I switch to patting at his face, then grabbing his muzzle and shaking it around, noticing how crusty the fur is, something I've never felt on Amicus before."
m "\"Amicus!\""
"I consider slapping him like I've seen people do in the movies, then I see the bottle next to his head and decide to go for another approach."
"I snatch it up and hurry to the bathroom."
scene bg bathroom with dissolve
"I hold the bottle under the faucet for a good five seconds, letting it fill up with soapy water to the halfway point before I hurry back out into the room."
scene bg amicusroomdim with dissolve
"Meanwhile, Com doesn't seem to notice me, droning on about how this particular emperor was known for having a fondness of orchids."
"I crouch down next to Amicus again, hesitating for a second as I wonder if maybe I should call Cato...probably not Cato...Neferu maybe, just in case Amicus is actually in trouble."
"I don't know how much a wolf can drink before it can kill them, but the sheer amount of bottles laying around the room worries me."
"I decide to just go ahead with my plan, and I upend the bottle over Amicus's face."
"It pours directly onto his nose and he immediately chokes, turning his head this way and that to avoid the stream of bubbly water."
"I have a moment to wonder if drowning him is the best approach before he suddenly sits up, pawing at his face."
show ami frustrated u with dissolve
a "\"Gah!\""
"The wolf covers his eyes and it's only then that I realize how irritating the soap might be for them."
m "\"Shit, sorry! Should I get some water from the shower so you can rinse your eyes out?\""
"Amicus freezes, still covering his face, then slowly lowers his paws to reveal his bleary, bloodshot eyes."
show ami surprised u with dis
play music "music/light years apart.ogg" fadein 5.0 noloop
"He stares at me in a way that he never has before."
"It's kind of surprised like Alex had been, but rather than fear, Amicus simply looks empty, numb."
m "\"Are you okay?\""
"I reach out, but Amicus turns his head away."
show ami cringe u with dis
a "\"Away with you ghost...enough of your torment.\""
"He keeps his head turned away, eyes closed."
m "\"Ghost? Amicus, it's me.\""
"I reach out and grab his face, and that seems to shock him as he jumps and turns to look me right in the eye."
show ami shocked u with dis
"I can tell that he's drunk, very drunk, but there's an extra distant look in his eyes that I don't like."
show ami surprised u with dis
m "\"Amicus...what are you on? Did you take something?\""
"I hold his big head steady, feeling the fullness of his cheeks in my hands, looking into his familiar eyes, no matter how glazed and unfocused they are."
hide ami with dissolve
"Then I find myself throwing my arms around his neck and leaning into his body, the reality of the situation crashing down on me all at once."
"Amicus gasps into my ear, as if my touch suddenly makes him realize that I'm real, that I'm here."
"Clumsily, he starts to stand up, pulling me up with him."
"It's difficult because I don't let go, almost getting lifted off my feet before I settle on letting go for just a moment to hug him lower, around his body, pressing my head to his chest, hearing his heart hammering inside."
"Finally, he's able to get a grip on me and push me away despite my intention to cling to him forever."
"He holds me at arms length, staring at me."
"I clutch his paws on my shoulders, staring up at him, feeling my eyes start to water."
show ami embarrassed u with dissolve
a "\"Is...is this possible? Is...no, please, I can't handle another hallucination.\""
"His expression keeps morphing from hope and awe to devastation."
"I feel his paws grip into my shoulders tightly, almost painfully, as if to make sure I'm real."
m "\"It's me! I woke up in the garden for some reason, I'm okay...\""
"I want to hug him again, but he keeps holding me away, looking me up and down, pushing my hair back and feeling my crusty skin."
a "\"But...but how...\""
m "\"I don't know. I just remember having crazy dreams, then I was in the garden.\""
stop music fadeout 10.0
show ami surprised u with dis
"As I'm talking, I think Amicus is finally believing it's me...and I notice that his body is starting to sway in a worrying manner."
m "\"Amicus?\""
"I reach out to steady him, but as I do, his eyes roll back and I realize there's no way in hell I'm going to be able to keep a wolf over twice my weight from toppling over."
hide ami with dissolve
"I try anyway, wrapping my arms around him as Amicus falls backwards, his bulk pulling me down with him before he falls back-first onto the bedside table, sending bottles flying while his upper-back and head smashes into the wall."
play sound "sfx/thud5.ogg"
with vpunch
"My fall is absorbed by his much softer front, but the sound is loud, the room shaking and probably waking up the entire palace."

scene bg amicusroom with fade
play music "music/dawn.ogg" fadein 3.0
"Waking the wolf up the second time is a lot easier, probably because he'd fainted rather than passed out from too much wine."
"We're at least able to move onto the bed where Amicus sits cross-legged, pulling me onto his lap and just holding me there, his paws moving around my body, still trying to make sure I'm real."
"For a moment, we don't talk, the wolf just pressing his nose to my hair and breathing in deeply."
"I feel a little self-conscious, knowing I must not smell very good right now, but that doesn't seem to bother Amicus as he goes on pressing his nose to my head and neck, taking in my scent."
"Finally, he does speak, but it's one word:"
show ami embarrassed u with dissolve
a "\"How?\""
"I turn my head toward the wolf, resting my cheek against his neck."
m "\"I don't know. I don't really even know what happened to me.\""
a "\"You got sick...so sick. You were having convulsions, brain and nerve damage, it was...it was terrible.\""
show ami sad u with dis
"Amicus's arms tighten around me, his voice, normally deep and strong, now sounding weak and broken."
"This statement worries me though, and I have to wonder if I really am better."
"There seem to be patches missing from my memory, and I do feel different, like I'm not fully myself, but I don't really want to think about it right now."
m "\"I think I remember a little bit of that. I had—\""
"I lift my arm up, showing Amicus the shiny, crusty scabs on my arm."
show ami embarrassed u with dis
a "\"It was avia pox, I—I can't believe I didn't consider the possibility of disease and illness for you. I'm just so used to the idea of any new arrival on Adastra going through that process...obviously we did it a bit differently.\""
m "\"Yeah...\""
show ami crossed serious with dis
a "\"And honestly I'm not even sure I'd have you do it. I don't know if you'd react differently to those vaccinations...each species has their own customized cocktail."
show ami embarrassed u with dis
a "\"And avia pox isn't included in the vaccination set. It's such a mild virus, we'd never seen anyone react to it the way you did, even other primates.\""
"I think back to how quickly I became sick, how quickly I almost died."
"I notice Amicus looking down at me again and I look back up at him."
m "\"What?\""
show ami sad u with dis
"Amicus shakes his head."
a "\"I'm just still trying to make sure you're here, that you're real...I—I'm afraid if I let go, if I even look away, you'll disappear.\""
"His arms tighten around me again, squeezing a huff of breath out of me."
m "\"I'm here, I promise.\""
show ami crossed serious u with dis
a "\"Well, I've had a lot of hallucinations; too many stress tablets I think.\""
m "\"Stress tablets?\""
a "\"Yes, quite a few of them in fact.\""
m "\"With wine?\""
show ami eyes u with dis
a "\"Oh yes.\""
m "\"Amicus!\""
"I don't really know what these stress tablets are, but I imagine mixing space Xanax with alcohol is a horrible idea."
"Amicus doesn't seem bothered by my reprimand though, instead just snuggling closer to me, his crusted face-fur prickly against my skin."
show ami u with dis
a "\"I love you, [mc].\""
"I get that familiar swooping feeling in my chest, like I'm on a roller coaster."
"I clutch onto his arms."
m "\"I love you too.\""
"Amicus sighs and sets his chin on my head."
show ami embarrassed u with dis
a "\"I thought I'd missed the opportunity to say it...I still can't believe you're real.\""
m "\"Well, I am. I promise.\""
a "\"But I still don't understand how. This shouldn't be possible. You were declared to be in a permanent coma, no brain activity...I had to set you out in the garden and only hope for a miracle.\""
m "\"Miracle?\""
"Amicus lets out a shaky sigh, running his fingers through my hair."
show ami sad u with dis
a "\"When a sapient falls into such a state, we simply let them...fade away in a peaceful setting, or possibly recover if the parent allows it.\""
a "\"I sat out there for a while, but couldn't bare to see you waste away, so came back to my room to drink and prepare for the emperorship.\""
"I imagine Amicus laying those flowers around me and I feel my heart break a little."
a "\"Did...did the parents come to you, is that why you're here? I had hope that they would.\""
"I shrug."
m "\"I really can't remember much.\""
show ami serious u with dis
a "\"It does not matter. My prayers were answered, praise the gods.\""
"Amicus starts to smother me again with his hugging."
"Little bits of imagery from my dreams is starting to come back to me."
"Something that happened in space, someone talking to me."
show ami crossed u with dis
a "\"And judging by the only human I know, your people are full of surprises. But we can figure it out later...I just want to hold you right now.\""
m "\"Okay.\""
a "\"...and [mc]?\""
m "\"Yeah?\""
a "\"Please try to avoid mentioning that I...lost consciousness when I saw you.\""
m "\"Of course.\""
"So we sit there for a while longer while Amicus just sort of cuddles with me."
stop music fadeout 5.0
"After about an hour, we finally decide to move to the shower, considering the state we're both in."

scene bg bathroom with fade
play loop "sfx/showerloud.ogg" fadein 3.0
"We shower together, taking turns scrubbing each other."
"The hot water really brings life back into my limbs, and those worrying tingles have faded to the point where I'm barely noticing them now."
"Amicus gently rubs at my crusted skin, and we're both surprised to see it come away, exposing new, unblemished skin underneath."
show ami surprised n with dissolve
a "\"Incredible. I never knew humans healed at such a rate.\""
m "\"...Yeah.\""
"I don't know if that's really the case, and my mind continues to wander back to those vague, hard-to-remember dreams I was having."
show ami eyes n with dis
"Meanwhile, Amicus leans back against the wall as I rub soap into his front, smiling gently as I lather up his chest."
"I can tell he's still fairly drunk, but that doesn't stop his cock from becoming fully erect between us, which I just pretend not to notice."
"His eyes widen as if he suddenly realizes something."
show ami surprised n with dis
a "\"Wait, did anyone else notice you?\""
"I pause, both my hands cupping his sizable pecs."
m "\"Yeah, actually. Alex was in the garden and I talked to him.\""
a "\"Just Alex?\""
m "\"Yeah.\""
"Amicus seems to relax a bit."
show ami serious n with dis
a "\"What did he say?\""
m "\"Just seemed really surprised—\""
a "\"Unsurprising.\""
m "\"—but he was acting a little weird.\""
"Amicus shrugs."
a "\"He keeps things to himself for the most part. I'd be worried if you ran into Cato, or Cassius especially. I need to think of a way to explain this to them. This Simian guise is becoming harder to keep up.\""
show ami happy eyes n with dis
"I'm about to mention more about Alex's demeanor, but that's when Amicus just starts hugging me again, his dick, hot and firm, crushing between us as he does."
"I don't care though, and Amicus doesn't seem to either."
a "\"I don't understand any of this right now, but as long as it's real, I don't care.\""
stop loop fadeout 3.0
"It feels so good like this, his wet fur slicked down tightly to his thick body which presses against me perfectly."
play background "sfx/showerfan.ogg" fadein 3.0
hide ami with dissolve
"Amicus finally shuts off the water and we're blasted with hot air."
"I'm dried in less than a minute and I stumble out to try and fix my poofy hair in the mirror while Amicus stands in the shower stall for a little while longer."
stop background fadeout 5.0
"After another few minutes, I watch him step out and come up behind me to nuzzle my ears, embracing me once again."
"He really can't keep his paws off me, but I completely understand why."

scene bg amicusroomdim with dissolve
"He starts nudging me out into the bedroom, before turning me around to face him, lowering his face to mine...and I finally realize where this is going."
"It feels so sudden, especially after everything that's happened, I think we could use more time to adjust...but I kiss back anyway."
"We've kissed a few times before, but only with our lips."
"Now, his tongue presses against my mouth and I only hesitate for a moment before letting it in, his thinner, longer tongue caressing mine with a surprising, nimble strength."
"I thought it would be kind of hard to make out with the way his muzzle is shaped, but Amicus makes it happen, his lips clamping around my mouth as he kisses deeper."
"I'm amazed at how bold he's being, and I wonder if maybe it's because he's still pretty inebriated."
"He cradles my head gently, walking me backward slowly, his cock poking against my groin and thighs occasionally until I come against the bed."
"Gently, he lowers me down to rest on my back, both paws coming to press on either side of my shoulders while he looms over me, grinning before he pauses."
show ami n with dissolve
a "\"Is this okay?\""
"I think."
m "\"I mean, are you okay? We can wait until tomorrow when you're less...drunk.\""
"He grins again."
a "\"I've been wanting to do this for so long, to show you how much I love you...\""
"Amicus leans down, nuzzling my neck."
show ami serious n with dis
a "\"I thought I'd missed that chance. I can't tell you how dark these past three days have been for me. I—I ran out of tears yesterday.\""
"Amicus looks away for a moment."
a "\"...I'm not going to miss that chance now.\""
hide ami with dissolve
play music "music/romance.ogg" fadein 10.0
"I reach up and hold his head steady again before I lean up to kiss him."
"This may be alcohol-fueled, it may be sudden, but after everything that's happened, after what Amicus has been through...I want us to be able to do this before anything {i}else{/i} happens."
"He huffs loudly through his nose, the burst of hot air tickling my face as he falls to the bed, rolling to the side to pull me up on top of him."
"His massive, soft body cushions me like it always does, rising and falling with his quickening breaths, his kissing becoming more and more aggressive as he lets out little growls and snarls."
"All the reservations I had about having sex with an alien wolf fall away at that moment."
"After everything that's happened, and especially after almost dying...I just don't care anymore."
"We grind against each other, both of us hard now as we just explore the other's body, his giant paws sliding up and down my sides while I do the same to him."
"Eventually, I sit up, straddling his waist, looking down at him, just sort of taking him in."
"Again, he has that silly grin on his face, his paws on my thighs, kneading at the skin and muscle."
a "\"You're beautiful.\""
"That makes me laugh."
m "\"Beautiful? Well, you're adorable.\""
"Amicus raises an eyebrow."
a "\"I'm not sure that's the correct descriptor for the next emperor of Adastr-aaahh!\""
"I lean forward and aggressively rub at his belly, his weak spot, immediately neutralizing his snark as his paws flop back above his head, eyes almost rolling with pleasure before he squeezes them shut."
"He writhes and arches around my hands, leaning into the rub as I slide my hands up to his chest, then all the way down to his lower stomach."
"When that happens, I feel his dick jump against my rear, making me realize how hard I'm getting him."
"I'm getting the same way as I make the strong, thick body below me undulate with pleasure."
"His head rolls from side to side, tongue flopping back and forth and when I giggle at him, that seems to finally bring him out of his trance."
"He growls and grips my arms."
a "\"THAT is cheating.\""
"With that, he rolls me over, easily reversing our positions as he mounts me, pinning my hands above my head with one paw."
"With his other, he tries to rub at my stomach, which makes me laugh and squirm until he finally lets off."
m "\"That...that doesn't work...on primates.\""
a "\"Seemed like it worked well to me!\""
"He lets go of my hands and leans down to nuzzle at my face, his cold nose exploring my chin, cheeks, and forehead."
"He then starts to adjust his positioning before he suddenly stops, looking up at me."
show ami embarrassed n with dissolve
a "\"Um...\""
"His ears lower, and I can tell that he's embarrassed."
m "\"What?\""
a "\"Do you humans...for males, do you go through the, uh...the rear?\""
m "\"Oh.\""
"I think about that."
"That would be the expected route, but looking at Amicus's length..."
"The wolf follows my gaze and looks even more embarrassed."
show ami disappointed blush n with dis
a "\"We don't have to! I don't want to hurt you, of course.\""
"I prop myself up on my elbows, looking between the two of us."
m "\"Yeah...maybe some other time. You're kinda thick.\""
"Amicus smirks."
show ami n with dis
a "\"Thank you.\""
"He starts adjusting himself again, squatting as he sort of waddles up so that our dicks are parallel to each other."
a "\"Maybe...maybe this?\""
"He slowly lowers himself until we make contact."
scene amiscene1 with slow_dissolve
"The feeling and sight of it is electric, the hot flesh of his cock pressing against mine firmly."
"Out of sight, I feel his furry balls come to rest gently on top of mine, the soft forms molding together easily."
"Amicus pauses there, smiling down at me gently as he rests both paws to either side of my head."
a "\"You'll have to excuse my ignorance. I'm not sure how humans might copulate.\""
"He wiggles his hips, causing his length to slide from side to side on top of mine, and I have to stifle a gasp."
m "\"I...I think it's about the same...from what I saw.\""
"Amicus frowns for a moment as he realizes what exactly it is I'm referencing, but quickly recovers as he leans down to kiss me once again."
"Once he's finished, I smile back up at him."
m "\"But yeah, this is fine.\""
"I rest my hands on his knees, noticing how he's balancing most of his considerable weight in a squat."
m "\"Are you comfortable though? That looks like a work out.\""
a "\"Heh, Cato works me a lot harder than this, [mc].\""
"Amicus frowns again as he realizes how that could be interpreted."
a "\"I mean, he makes me do a lot of squatting exercises. I'll just consider this extra practice.\""
"I reach out and feel up the wolf's chest and belly while he speaks, again marveling at how powerful it all is."
"Amicus chuckles and arches out a bit to give me a better feel, taking deep breaths and puffing out his chest."
"He shudders as I rub at his nipples, the nubs of flesh hardening instantly."
a "\"Mmmh...so, now that you're comfortable—\""
"Tentatively, Amicus reaches down with his left paw and carefully lifts my length from my stomach to press against his."
scene amiscene2 with slow_dissolve
"This time, I let out a little gasp, being squeezed together like this sending a jolt of pleasure up from my dick, through my body, and into my brain."
"Immediately my skin breaks out into goosebumps as I shiver to Amicus's touch, his gentle, but all-enveloping paw feeling so good right now."
"He starts off slowly at first, beginning to jerk us both off in small, quick motions."
"I can tell that he's being overly-careful with me, so I jerk my hips up against him, encouraging more."
"He seems to get the hint, and he picks up speed, giving the two of us deeper, faster strokes that makes me grip at the bedsheets on either side of me, staring at the ceiling as I let out soft pants and groans."
"Amicus gets more and more into it, already leaking all over my own dick as he pumps his paw, bicep bulging with the effort."
"I've been jerked off by others before, but Amicus's paw really is something else."
"Of course it's big, but the soft, squishy pads on his palm and fingers add to the pleasure, giving me a texture I've never felt before."
"The wolf starts to thrust his powerful hips into the stroking, making the bed squeak and shake."
"Again, his strength is evident in how he practically moves my entire body with each thrust, the idea that he's holding back turning me on even more."
"I feel his heavy sack bouncing on top of mine."
"My knees jerk up with each thrust, and each time they do, I feel his large rear-end slam up against them, its furry form tight and clenched."
a "\"I'm...getting...close...\""
"He pants out over my head, a drop of drool dripping down onto my cheek."
"I start to thrust up against him in earnest, wanting to match his climax."
"At this point, we're almost bouncing on the bed with how hard the wolf is humping against me, forgetting his strength in the moment."
"I don't mind though, not really caring how sore I'm going to be tomorrow as the pleasure overtakes me."
"It hits me all at once and I reach up to put a hand against his face, letting him know, and he takes that as his signal to let go as well."
"I feel it in his entire body, the wolf tensing up, muscles tightening, standing out through the fur on his thighs, stomach, and chest."
"I see his face then as he balances on the edge of climax, eyes wide and looking toward the ceiling, mouth hanging open, a look of pure awe."
"I feel it in his cock too, and at the same time, we're both pushed over the edge."
scene amiscene3 with slow_dissolve
"I groan, something I don't usually do, but the build-up, the situation, the feeling is all too much."
"It's drowned out by the sound that Amicus makes though."
"He practically sags over me, letting out a bassy, rumbling moan of ecstacy."
"Hearing the masculine, deep voice making a sound of such pleasure spurs on another spasm from my cock."
"I think the same happens to Amicus, because he suddenly hunches forward again, muzzle right next to my ear as he groans out again, his hot rush of breath on the side of my face making me shudder."
"The big wolf continues to thrust against me, in time with the spurts from his cock, the look on his face now one of goofy pleasure, his long tongue drooping out, dripping onto my chest."
stop music fadeout 10.0
"His climax goes on for several seconds longer than mine and I watch as he spurts over my stomach over and over until finally he collapses down against me, his fur damp with sweat."
"I wrap my arms around him as he heaves for breath, feeling his body expand and contract against mine."
"He nuzzles against my head, his stomach flattening against mine, against the mess we've made."
"We're going to have to take another shower."
scene bg amicusroomdim with dissolve
"Even though I'm a bit out of breath, I'm kind of amused at how much Amicus is gasping, sounding like he just ran a marathon."
"He really put everything into that."
a "\"Huh...huh...you...\""
"I hold his head against mine, turning to kiss him on the cheek."
m "\"Me?\""
a "\"You...are...incredible...\""
m "\"Thanks...you're really something too.\""
a "\"A...good something?\""
m "\"A very good something.\""
"We lay there quietly for a moment, Amicus propping himself up a bit on his knees and elbows so his entire weight doesn't rest on top of me."
m "\"How are your legs?\""
a "\"Heh, burning. Probably the most intense exercise my thighs have ever been through, but it was worth it.\""
"Again, we lay there quietly as Amicus just sort of strokes my hair."
a "\"I'm still terrified that this a dream.\""
"I hug him more tightly to my body, almost forcing him to fall on top of me."
m "\"I'm here, and I'll be here in the morning when you wake up.\""
a "\"You'd better, otherwise I'll never forgive you.\""
"His speech slurs a bit as he whispers into my ear."
"I look at him."
m "\"So exactly how drunk are you?\""
"The wolf shrugs, slowly rolling off of me, cold air hitting the fluids on my stomach."
show ami happy eyes n with dissolve
a "\"I'm fairly sober now. Shall we wash up?\""
"He reaches out a paw and I take it, slightly surprised as he pulls me up to be carried in his arms, like I'm his new bride."
hide ami with dissolve
"We go to the shower and wash up again, even more slowly than we did the first time."
"When we come back to the bed, Amicus continues to dote over me, hardly ever letting me go at any point."
"I can tell that he is legitimately worried that this isn't real, and I feel the same way."
"After everything that's happened, this doesn't seem possible."
"Eventually, I lay in the bed next to him, and he spoons me tightly against his body."
"He's extremely warm, but with no blankets and the cold air drifting down on top of us, it's perfect."
"Pretty soon I'm drifting off to sleep, listening to the wolf's soft snores in my ear."
"Thankfully, I don't dream..."
scene bg black with slow_dissolve
"..."

scene bg amicusroom
"\"GET UP!\""
"I jump at the same time I feel Amicus jolt against me."
"We both struggle to sit up while pulling the covers up around us."
show cat angry with dissolve
ca "\"OUT OF THE BED!\""
"The jarring appearance of Cato has me staring at him in surprise, unsure of what to do."
"Amicus immediately moves though, pulling me off the bed with him, standing slightly in front of me as he hands me the blanket to cover myself up."
"We both stare at Cato, the old wolf actually shaking with fury."
ca "\"Make yourself decent, Amicus.\""
"Amicus hurriedly snatches up underwear from the dresser, giving me one of my own as well."
"As I'm struggling to tie mine on, I notice Cassius standing in the doorway, something shiny and flashing with lights in his paw."
"He doesn't have the usual sour look on his face though."
"Instead, he almost looks scared."
"Cato lets us stand in silence for a moment before turning his head toward the door."
ca "\"Felix! Enter!\""
"I hear shuffling around out in the hallway and Cassius moves to the side to allow a neatly-robed wolf to enter."
"He looks about as old as Cato, though nowhere near as big."
"He moves timidly, looking about with his ears down."
"Felix" "\"Y—yes, your Imperial Majesty?\""
ca "\"Is that the alien you treated for avian pox?\""
"Cato jerks his head at me, keeping his eyes on Felix."
"Felix turns to look at me, and I can tell that he's trying to think of the right thing to say."
"Finally, he just gulps and nods his head."
"Felix" "\"Yes, I treated him three nights ago for avian pox.\""
ca "\"And his species had no profile?\""
"Felix" "\"N—no, I could only tell that he was a primate...how...how is he conscious—\""
ca "\"Com, escort Felix to the dungeons.\""
play music "music/tension.ogg" fadein 3.0
com "\"Yes, Cato\""
"Felix" "\"What? Why!? Why to the dungeons...Your Majesty?\""
"Felix looks imploringly at Cato before the probes enter."
com "\"Proceed to the hall or risk being shot, Felix.\""
"Felix" "\"Please, what is happening?\""
"Even while he speaks, Felix backs away out of the room, Cato completely ignoring him."
"We all listen to the doctor's stumbling steps out in the echoing hall, the wolf making an attempt to ask Cassius what's happening before things fall silent again."
ca "\"Cassius, come in and close the door.\""
show cas scared at zero with dis
play sound "sfx/doorclose.ogg"
"Cassius, looking even more scared now, steps inside and allows the door to close."
"Cato stares at the two of us."
"At this point, Amicus has one paw on my arm, keeping me firmly halfway behind his back."
"I'm still able to look around his shoulder at the furious acting emperor."
"Slowly, I'm starting to realize what might be happening right now, and Cato's next words confirm it."
show cat frown with dis
ca "\"Amicus...did you make First Contact?\""
"Amicus is silent for a beat, but responds in a strong, confident voice."
show ami serious u at twelve with dissolve
a "\"No, of course not. What in the world are you talking about, Cato?\""
"Cato stares, jaw clenched, then screams at us at a volume I didn't think he was capable of."
show cat angry with dis
show ami surprised u at jumping with dis
with vpunch
ca "\"DO NOT PLAY GAMES WITH ME AMICUS!\""
"To his credit, Amicus only jumps a little bit, his grip still firmly on my arm."
"The silence that follows rings in my ears as Cato seems to work to calm himself down."
"When he speaks again, his voice is barely above a whisper."
show cat bow with dis
ca "\"He is un-profiled. ALL children, abandoned or not, are profiled. He is not a Simian, so WHAT is he?\""
"Amicus is frozen, and I feel my stomach drop, like I'm going to piss myself."
"I see Cato working his jaw."
show cat angry with dis
ca "\"And is it true he's your lover?\""
"Lover?"
"How would he know anything about that?"
"Amicus doesn't answer this time, and that seems to be enough for Cato."
ca "\"Fine, do not answer. We will take the correct precautions. COM!\""
com "\"Yes, Cato?\""
ca "\"Terminate [mc].\""
show ami shocked u at jumping with dis
a "\"NO!\""
show ami angry u with dis
"Amicus simultaneously throws himself in front of me while reaching back and hugging me to him with both paws, backing me against the wall."
"Drones begin to enter the bedroom, but Cato barks out another order."
ca "\"Pause last directive!\""
com "\"Pausing last directive.\""
"My view is obscured now, but I can hear Amicus's heavy breathing, his heart hammering so hard that I can feel it through his back."
"Once again, Cato allows the silence to stretch out before speaking."
show cat frown with dis
ca "\"Then tell us the truth, Amicus.\""
show ami angry teeth u with dis
a "\"You must not harm him! Otherwise, I will give you nothing and...and I'll have you thrown in the dungeon when I become emperor!\""
"More silence."
"I wince, wondering how that could have possibly been the right thing to say."
"Then I hear a low growling sound, one I'm sure is coming from Cato."
show cat angry with dis
ca "\"How dare you. You think you'll become emperor after this? In fact...\""
"I hear a quick movement and the next thing I know, Amicus is wrenched from in front of me."
hide ami 
hide cat
with dissolve
play sound "sfx/thud.ogg"
with vpunch
"I watch as he slides across the floor before Cato pounces on him, pinning him there."
ca "\"Cassius! Grab the alien! Set the nervo to lethal.\""
a "\"NO! PLEASE!\""
"I'm frozen, but I manage to look over at Cassius who seems just as frozen as I am, holding up the nervo in his trembling paws."
ca "\"MOVE YOU IDIOT!\""
show cas scared at twelve with moveinright
"Cassius jumps and hurries over to me."
"I start to pull away, but he grabs me up in an awkward hold, setting the nervo against my neck."
a "\"NOOO!\""
"Amicus's struggles double and Cato is bucked around like he's on a mechanical bull."
ca "\"Cease struggling, Amicus! He will not be harmed if you do as I say!\""
"Amicus seems to calm down a bit at that, panting wetly against the floor as he looks straight at me, face full of desperation."
ca "\"You've proven yourself to be an incompetent fool, even moreso than I'd originally thought. You've endangered our entire empire. For this, you will not become emperor, rules be damned.\""
ca "\"It's a wonder how you thought you'd get away with this. It can only be a miracle that the monitors have not found out, and they surely would if you became emperor with that...thing.\""
"Cato stands and wrenches Amicus to his feet, twisting the other wolf's paws behind his back hard enough that Amicus lets out a bark of pain."
show cat at four with dissolve
show ami cringe u at one with dissolve
ca "\"The third trial begins today. You will lose, and Cassius will become emperor.\""
"Cato begins to push Amicus to the doorway."
ca "\"Do as I say, and I will let the alien live, otherwise we can do all of this in the most unpleasant way possible, understand?\""
"Amicus is quiet until Cato shakes him by his pinned arms."
a "\"Agh!...Yes.\""
ca "\"Good, now to the amphitheater. We will do this quickly. Do not make any stupid moves otherwise I will let the drones escort you instead.\""
"Cato presses Amicus toward the door."
show ami embarrassed u with dis
"I see Amicus glance back at me, the look on his face one of utter helplessness."
hide cat
hide ami
with dissolve
stop music fadeout 10.0
"They're out the door by the time Cassius realizes he's supposed to be following."
"He jumps before awkwardly pushing me after them."

scene bg amphitheaterevening with transition_fade
play music "sfx/forest.ogg" fadein 5.0
"It's already sunset when we get to the amphitheater."
"We must have slept for most of the day."
"Amicus and Cato are already standing in the center of the amphitheater as Cassius struggles to move me down the steps."
show cat angry at center with dissolve
ca "\"Sit him down, Cassius, and get down here!\""
"Shakily, Cassius plants me down on one of the stone steps before suddenly undressing."
"That's when I notice that he's tucked the nervo into his waistband."
"Possibly because of the frantic nature of the whole situation, Cassius seems to have forgotten it, and I watch it fall into his clothing as he drops it from his waist."
"He then stumbles his way down to the center."
"Amicus, meanwhile, stands stiffly next to Cato, his paws clenched, and I feel my heart sink as I see the look on his face."
"He has no idea what to do."
"Several camera drones had followed us to the amphitheater, their lights glowing an ominous red."
"For several moments, Cato watches them arrange themselves around the small theater, their lenses flashing in the fading light."
show cas scared u at one with dissolve
c "\"Cato?\""
ca "\"What, Cassius?\""
c "\"There was no trial scheduled for today...how will this be broadcast anywhere?\""
ca "\"This will not be live. I'll think of a reason to tell the people later. We only need a single clip of you being victorious.\""
show ami crossed serious u at twelve with dissolve
a "\"They will never believe this.\""
"Though Amicus is putting on a brave face, I can hear his voice shaking."
ca "\"{i}Pugnu{/i} is a combination of skill and luck, and it's not always the strongest that wins. We will manage.\""
a "\"And how—\""
play sound "sfx/thud2.ogg"
hide ami with dis
show cas scared u at jumping
"Cato suddenly whirls on Amicus, throwing a punch so hard into his jaw that the other wolf spins almost 360 degrees before collapsing on the hard floor of the amphitheater."
"I'm standing up without even remembering doing so, heart hammering in my throat as I look down at Amicus."
"He doesn't move."
"Meanwhile, Cato shakes his paw lightly, like it only stung a little bit."
"Cassius, on the other hand, is clasping both his ears in his paws, staring down at his brother in a mix of shock and horror."
show cas furious u with dis
c "\"C—Cato! What are you doing!?\""
show cat talking with dis
ca "\"Making it look more authentic, is all.\""
"Amicus stirs on the ground then, groaning and pushing himself up."
"I see dark spots forming under his face, blood dripping from his nose."
"A camera drone drifts down slowly, filming Amicus as he spits blood."
"I realize then that I have to do something."
"I've been told to sit on the sidelines for far too long."
"And I'm not entirely convinced that I'm going to be okay after this."
"I'm a risk to the entire empire."
"Why would Cato let me live after I'm done being useful?"
"I {i}have{/i} to do something."
"So I quietly sit back down and lean over to reach into Cassius's pile of clothes, quickly finding the nervo and pulling it out."
"Then I stand back up again to take a step downward, and no one seems to notice."
ca "\"Come on Amicus, get up. You need to grapple with Cass.\""
show cas disappointed u with dis
c "\"Why didn't we just use makeup instead?\""
ca "\"There is no time.\""
"Cato finally bends down to grab Amicus under the arms and heave him up to his feet, the big wolf left to stumble unsteadily, blood running down his chin."
ca "\"Cassius, get Amicus in an ankle lock and drop him. That should be enough.\""
hide cat
hide ami
hide cas
with dissolve
"They set up their scene, even though Amicus seems almost completely out of it."
"All of them are distracted, and I realize that this might be my only chance."
"Slowly, I take one step at a time, down toward the center of the amphitheater."
"Meanwhile, Cassius is struggling to pick up Amicus's leg, almost losing his own balance as he does."
"After that, Cato tells Amicus to fall back, which the wolf does, slowly."
"Cassius pins him on the ground after that, and I don't think it looks convincing at all."
"But that doesn't really matter now as I'm only a few steps from the ground floor."
ca "\"Now, stand and raise your paws in victory, Cass. Look proud.\""
"At this moment, things start to move in slow-motion."
"Amicus is flat on his back, but he's looking right at me."
"There's a questioning look in his eyes, then a pleading one, as if urging me to step back."
"I don't."
"Instead, I take the final step down onto the floor of the amphitheater, just behind Cassius, moving towards Cato."
"But the white wolf continues to celebrate his pretend victory, and he turns with raised paws to face me."
"I see the sudden recognition on his face."
"I run out of options and jam the nervo right into his chest."
stop music fadeout 5.0
play loop "music/tensebackground.ogg" fadein 3.0
"Instantly, Cass is shot backwards several feet to crumple next to Amicus, shivering and convulsing."
"Before I can even turn to Cato though, the old wolf is on me, grabbing the nervo out of my hands and pulling me close by the front of my robes, my teeth clacking together with how fast he does it."
"He's looking at the nervo rather than me, though."
show cat angry with dissolve
ca "\"Damn it! Thank the gods the idiot didn't have it set on lethal.\""
"Cato fiddles with the device and I realize he's about to use it on me."
"I struggle, kicking at the massive wolf, but he's strong, stronger than even Amicus."
"But just as he flips the device around, the two metal prongs pointed at my face, I see a paw come over the top of Cato's head."
"Amicus grips into the metal grating of Cato's face mask, fingers locking into the gaps before he pulls."
hide cat with dissolve
"Cato screams, and I hear a horrible mix of crunching, tearing, and an electronic hiss as I see red spurt from the old wolf's face for just a moment before he goes down."
"Amicus stares at me with wild eyes as he tries to keep Cato pinned."
a "\"[mc], run...run to Neferu! RUN!\""
"I stare at Amicus numbly for a moment, a moment in which I want to do so much...but can't, then turn and start to run."
"I run as fast as I can, disappearing behind the trees and bushes, just as I hear Cato yelling for Com to execute me."
jump a2s2

stop loop fadeout 5.0
scene bg black with transition_fade
"To be continued..."
window hide
scene bg credits with dissolve
pause
stop sound fadeout 3.0
return


