label a2s3:
"Behind me..."
"There is no \"behind me\" because I don't have a body anymore."
"Instead, the feeling creeps just outside of my awareness."
"Whenever I try to focus on it, it slips away."
"So instead I just let it go, floating in space, feeling almost nothing."
"And feeling nothing right now, after everything, feels good."
"But after a moment, I start to get vague, far-off feelings."
"Not my own feelings, but the feelings of others, and I pick them up like distant whispers."
"\"We've interfered far too much already.\""
"\"Nothing goes to plan with the wolves. It must be done...\""
"I'm only half-listening, coasting on the waves of soothing, empty space."
"If this is how the drug makes you feel, I'm pretty into it."
"\"The more we interfere the harder it will be to predict anything.\""
"\"There is no other choice.\""
"The voice-feelings cease at that point, and I continue to ripple on the waves of the universe."
"That's when I notice something appearing in the center of my infinite space."
scene watching with slow_dissolve
"I've...seen this thing before...I think."
"Dreams that had fled my mind the moment I'd woken up suddenly come flooding back."
"I focus on this being, this creature that's been following me since I was abducted."
"He looms there, staring at me, even though I'm everywhere at once."
"The silence goes on for a while...or maybe not."
"I still don't have any sense of time."
"That is until the creature speaks."
play music "music/memories.ogg" fadein 10.0
unk "\"[mc].\""
"The voice is deep and masculine, rumbling through my being."
"I wait a moment, then try to acknowledge him, made difficult by the fact that I don't have a mouth to speak with."
unk "\"If you wish to communicate then do so. I can hear you.\""
"\"What?\""
"I try to think the word at him, but it's slow and clumsy in my mind, and I just wish that I could talk."
"There's a rumble of amusement through the air."
unk "\"If you desire a body, simply will it to be. The loss of self is a disturbing feeling for you creatures, I know.\""
"What he's saying doesn't make all that much sense, but I try anyway, and just like that, I feel my being start to pull together."
"I start to materialize right in front of the creature, and I see my hands in front of myself again."
"When I look down, I see my body, naked."
"As soon as I see that, I feel a shock of embarrassment, and my robe suddenly appears on my body."
"I still don't feel right, like I'm still not in this body that I see."
"Still, it does feel better, and I'm able to open my mouth."
m "\"What is this?\""
"My mouth feels strange and rubbery, and at the same time it feels like cotton is coating the inside."
unk "\"This is...\""
"For the first time, the creature seems unsure of what he should say."
unk "\"Well, it's a bit complicated to explain, but it's simply a space where you and I might be able to communicate peacefully."
"That's not really an answer."
unk "\"No, but if I were to explain it in-depth, it would waste the small amount of time we have together and confuse you even further.\""
"I try to stay focused, wanting to know as much about this guy as I can before the drug wears off."
m "\"You're a parent?\""
"That rumbling laughter tickles at the edge of my existence again."
unk "\"No, definitely not. I am a monitor.\""
"Monitor."
"Icy fear trickles down my imagined spine as I realize what this all might mean."
"The monitor quickly holds up a paw."
mon "\"No, no, don't worry. You're not in trouble.\""
"I watch him cautiously, as if he's only lulling me into a false sense of security before annihilating me on the spot."
"Again, that feeling of amusement."
mon "\"Now that would be impossible to do here.\""
"I try to keep my thoughts focused."
m "\"What about Amicus? Is he in trouble?\""
mon "\"No. He only did what we had planned for him to do.\""
m "\"Planned?\""
"There's a pause, as if the monitor is gathering his thoughts."
mon "\"No, I'm simply receiving instructions.\""
m "\"From?\""
mon "\"The parents.\""
"I stare at him."
m "\"They're talking to you?\""
mon "\"Yes, about you and what I can and cannot tell you.\""
m "\"Why don't {i}they{/i} just talk to me then?\""
mon "\"Because they cannot. Direct communication is impossible.\""
m "\"Then how—\""
mon "\"I was specifically designed to be a bridge between your...let's say dimension, and theirs.\""
"I don't really know what to think about that, but I get the feeling that I shouldn't be distracted by these things right now."
mon "\"That would be wise.\""
m "\"So what do you mean 'planned'? The parents set Amicus up somehow?\""
mon "\"Your abduction and introduction to the wolven empire was meant to happen.\""
m "\"Why?\""
"Another slight pause."
mon "\"The wolves could single-handedly undo the {i}Galaxias{/i}, but you can change that.\""
"I frown, feeling some anxiety slip through the drug-induced calm."
m "\"What? How?\""
mon "\"The wolves are...a stubborn sibling, possibly a mistake made at the very beginning, but the parents can still see the correct path and destination.\""
m "\"See? Can they see the future, or something?\""
mon "\"In a way, yes. Their minds exist in many times at once.\""
"I'm starting to become lost and suddenly, I begin to feel like a primitive life-form, incapable of understanding this ancient, alien monolith before me."
mon "\"Do not feel that way. You yourself may not understand, but your species as a whole is more than capable.\""
"My mind automatically thinks back to how we were abandoned by the wolves, by maybe even the jackals too."
mon "\"You were abandoned by all the siblings.\""
"For a single moment, multiple images of several different creatures cross my mind; a bear, a wolf, a jackal, a lion, a ram..."
"They're all recognizable, and what they wear is recognizable too, reminding me of several different cultures on Earth."
"The images finally stop on a tiger in a flowing dress with intricate designs and patterns, and what looks like a sari draped over her shoulder."
"As the image fades from my mind, somehow I know immediately that it's Meera."
mon "\"Yes, we reigned in the wolves once before with the help of the Hindos, but it lasted for a far shorter period of time than we'd foreseen. That's why we've turned to you, to play her ancient role.\""
m "\"But...we're not part of the {i}Galaxias{/i}. Everyone failed at uplifting us, so isn't something wrong with us?\""
"Another pause."
mon "\"In a way, yes, but after the attempts, all of the parents realized that humans would factor into the {i}Galaxias{/i} later...now.\""
m "\"All? Aren't the parents competing with each other?\""
"This time I only get silence in response."
"I wonder if he's just been told that he can't tell me that."
m "\"So...what am I supposed to do? What do you want with me?\""
"The answer this time is immediate."
mon "\"Restore Amicus to his rightful place on the throne.\""
"I wait, but there isn't any other explanation."
#
m "\"And...how do I do that?\""
"Silence."
m "\"Why me?\""
"More silence."
"I blow out air in frustration, or try to since nothing comes out."
m "\"Why can't you all just {i}tell{/i} me what to do? You brought me here, didn't you? Just tell me.\""
"Nothing."
"I'm about to just give up, wait out the trip when the monitor begins speaking again."
mon "\"Interference often leads to destabilization of the events that should follow. The {i}Galaxias{/i} must develop and learn in its own way.\""
m "\"Except for now, right? This is interfering, isn't it?\""
mon "\"Except for in various instances where the children and siblings stray too far off course.\""
"This time I'm the one left unsure of what to say."
"I'd always seen the parents as all-knowing beings with only good intentions for their children, but now..."
"How do I know they can even be trusted?"
"What I do know is that the monitor is apparently able to hear all my thoughts, so he definitely heard that."
"Still, he doesn't say anything, just regarding me silently."
m "\"So...I guess you can't tell me what the purpose of all of this is, then? The {i}Galaxias{/i} as a whole?\""
mon "\"That knowledge has not been earned by the sapients yet.\""
"My mistrust grows."
m "\"Well...can you give me something, {i}anything{/i} that might help me with getting Amicus out of the dungeon? If I'm straying off the course then tell me how to get back on it.\""
"The monitor pauses for a moment, as if getting more information from the parents."
mon "\"Watch the cat.\""
"The cat."
m "\"Alexios?\""
"I wait, but again I get silence."
"I shake my head."
"If the parents really are all-knowing and all-powerful, then why can't they just tell me—"
mon "\"We are neither of these things, hence why we must be so careful.\""
"I just stand there, unsure of what else to do."
"I look around."
m "\"Is uh, is Cassius alright?\""
mon "\"The false emperor? Yes, he's somewhere around here.\""
"The monitor looks about dismissively."
m "\"Did he hear us?\""
mon "\"No, he's too busy panicking. A side-effect of being a coward imposter.\""
"I frown, feeling that's a bit harsh, even on someone like Cassius."
m "\"Can you...can you help him, maybe bring him here?\""
"I get a feeling from the monitor that I can only describe as an annoyed sigh."
mon "\"I suppose.\""
"A few moments pass before I start to see something appear next to me."
show cas scared at fourteen with dissolve
"The unmistakable shape of Cassius materializes, frightened and shaking."
"He immediately sees me."
show cas scared at my_shake
c "\"[mc]!? Where are we? What's happened? Are you—\""
"Then he sees the monitor."
show cas scared at jumping
c "\"Agh!\""
"He jumps behind me, shielding himself from the creature."
c "\"The demon! Help me!\""
"I get that feeling of amusement from the dragon creature again, and I frown."
m "\"Have you been scaring him?\""
"I get the feeling of a shrug from the creature."
mon "\"If he's scared that's his choice.\""
m "\"And the parents are okay with you doing that?\""
mon "\"Possibly not, but the white wolf means little to them.\""
show cas angry with dis
c "\"What?\""
"That seems to get Cassius's attention, and he pokes his head around my side to glare at the monitor."
ca "\"E-excuse me, but I am the emperor—\""
mon "\"No, you are not.\""
"I frown, the scene growing more and more surreal before me."
show cas surprised with dis
c "\"Excuse me!?\""
stop music fadeout 10.0
"Cassius seems unable to think of anything else to say."
"Just as I'm about to step between the two of them, I find myself unable to hold my consciousness together any longer and I begin to drift off..."

scene bg amicusroom with transition_fade
"Slowly, I come to on the sofa, my eyes cracking open as I wince at the throbbing headache I have."
"There's a cold sensation around my mouth and I reach up to feel that I've been drooling all over myself."
"I roll over, feeling a wave of dizziness as I do."
"I pause there, waiting for the wooziness to pass."
"When it finally does, I'm able to focus better on my surroundings."
"I stare a full ten seconds before I remember where I am, and what I'm doing there."
"I look over at the bed and see Cassius lying spread-eagle on the covers, his eyes fluttering."
"I watch him for a while, realizing that he's still unconscious."
"He did take in a lot more of the drug than I had, so I guess that makes sense."
"Very slowly, I slide my legs off of the sofa and sit there as a second dizzy spell overtakes me."
"I wait a solid minute for this one to pass so that when I stand up I don't end up just falling over."
"When I'm able to do that, I stumble to the bathroom, feeling more and more clear-headed by the second."
scene bg bathroom with dissolve
play sound "sfx/dooropen.ogg"
"When I get to the sink, I rest there, staring at myself in the mirror."
"My eyes are red and my hair is messed up in every direction."
"I wet one of the towels and wash my face and by the time I'm finished, I feel mostly better."
"As I rest there against the sink, I think back to what just happened."
"Not just the drug trip I'd been sent on, but what I'd been told."
"All the dreams I'd had since being on this moon; I remember everything."
"I don't know if it's real or not, if I'd really just spoken to the parents."
"It had seemed too intricate to not be real."
"My mind wouldn't be able to make up something like that, would it?" 
"Then again, I don't know what Cassius was smoking."
"As if on cue, I hear the wolf snort in the bedroom and I make my way out of the bathroom, finding Cassius on his side now, facing away from me."
scene bg amicusroom with dissolve
m "\"Cassius?\""
"Slowly, I walk around the bed and see that the wolf's eyes, just as red as mine, are open, staring off into space."
"I try again."
m "\"Cassius? You okay?\""
"The wolf mumbles something, not even looking at me."
"I walk up to the side of the bed, reaching out tentatively before gently touching him on the arm."
"That seems to jolt him from his daze and he jerks away, gasping in surprise and fear as he pulls back and looks up at me."
"I hold my hands up to show him that I mean no harm, and he stares at me for what feels like over a minute."
"Finally, he mumbles out my name."
show cas annoyed with dissolve
play music "music/dawn.ogg" fadein 3.0
c "\"[mc]...\""
"I nod slowly, not wanting to make any sudden movements."
m "\"Yes, I'm [mc]. You're in the palace, in Amicus's old ro—\""
show cas angry with dis
c "\"I know where I am, idiot.\""
"Seems like he's returning to his old self."
m "\"Well, that's good. You had a pretty bad reaction to...whatever that was.\""
"Cassius is pushing himself up to a sitting position, doing it slowly just like I had."
show cas dissapointed with dis
"He lets his head hang for a while, probably going through the same dizzy spells I'd just experienced."
"I wait patiently, deciding to move back over to the sofa while I do."
"His ears perk up as I sit down, and he looks back up at me."
show cas annoyed with dis
c "\"What are you doing?\""
"I frown."
m "\"What do you mean?\""
show cas with dis
c "\"I mean why are you still here? You may leave.\""
m "\"Uh, I guess I could. I just want to make sure you're okay first.\""
"Cassius lets out a soft, indignant snort."
show cas paw with dis
c "\"You think I believe that? You're dismissed.\""
"I give him an incredulous look."
m "\"Seriously? First of all, this is Amicus's room, second, I'm a Khemian. I don't see you ordering Neferu around like that.\""
"This time Cassius lets out a louder snort."
show cas paw annoyed with dis
c "\"Ha! He's royalty, and an actual Khemian, you think that I'd pay you the same—\""
m "\"Khemians see all their citizens as equals. I'm worth just as much as he is in their eyes.\""
"Instead of snapping back, Cassius just lowers his head, eyes closed before he lets out a deep, forlorn sigh."
show cas disappointed with dis
c "\"I'm tired, if you wish to antagonize me please leave it for another time.\""
"I've been pushing the boundaries with Cassius on purpose to see what the limits are, and I'm getting more comfortable conversing with him without fear."
"Still, I'm a bit taken aback at Cassius's sudden tone of defeat."
"It's one that I haven't heard often."
"We're both silent for a minute or so, then I finally speak up."
m "\"Um...so what was that? That smoke stuff? It was a drug, right?\""
"Cassius is silent for a bit longer, and I wonder if he's going to ask me to leave again, but instead he just sighs and finally looks up, his eyes looking a bit more clear now."
show cas with dis
c "\"It's called {i}somni{/i}, a plant from the southern region of this continent. It helps us connect to the parents.\""
m "\"Yeah...you said it's the traditional way?\""
c "\"The old way, yes. Usually we communicate through parental tech, but as you know, they're not currently speaking to with us with that method.\""
m "\"Sooo...this forces it to happen?\""
c "\"In a way.\""
m "\"Does it work?\""
show cas annoyed with dis
"Cassius glares at me."
c "\"You would know. You were there.\""
"I go silent, that statement coming as a surprise to me."
"I'd seen Cassius, of course, but I'd thought it had only been part of the hallucination."
m "\"You...saw me?\""
c "\"Oh please, simian...or whatever the hell you are. You're only trying to humiliate me further. I was right next to you.\""
"So that had been real?"
"I sit back on my hands, contemplating all of this."
"I've read about DMT experiences back on Earth, how if you break through, you can meet extra-dimensional beings that tell you the secrets of the universe."
"I would have considered my experience to be all in my head, but if Cassius was actually there..."
show cas righteyes with dis
"I notice then that Cassius is looking very closely at me, gauging my expression."
m "\"What?\""
c "\"He spoke to you, didn't he? What did he say?\""
m "\"Uhhh...\""
"I try to think of what to say."
"If this is real, then I doubt telling Cassius everything will help me out in any way."
"He must see the hesitation on my face, because his fur bristles."
show cas furious with dis
c "\"The emperor demands you tell him what they told you!\""
"I glance up at Cassius, feeling less and less afraid of him with every threat he sends my way."
"He really is all bark and no bite."
m "\"He just sort of asked me what I was doing there. That's it.\""
"Cassius glares at me before finally seeming defeated once again, looking down."
show cas disappointed with dis
m "\"But he seemed okay with me being here. He was a monitor too. I don't think Amicus is in trouble.\""
"Cassius shakes his head."
c "\"I don't trust anything he said. He was a demon.\""
"I sigh."
m "\"What did they say to {i}you{/i}? You looked pretty scared.\""
show cas annoyed with dis
c "\"I was not scared!\""
"I let out an involuntary laugh before I can stop it."
show cas angry with dis
c "\"Damn you! I was simply unprepared for the experience; it was much more intense than the previous one I had. That's all.\""
show cas disappointed with dis
"Cassius looks at the ground again, and I can see that the insides of his ears are a burning red."
"I know that laughing at him was a shitty move on my part."
"I should be working to get him on my side, to help Amicus."
"I make an effort to get my expression under control."
m "\"Listen, I'm not against you Cassius. Actually, I think we're working together here. I'm just...trying to figure out how best to help your brother.\""
"Cassius continues to stare silently at the floor, though I see an ear twitch as if acknowledging what I'd just said."
m "\"If we're going to work together, we need to be at least a little bit honest with each other. Maybe I could help you figure some stuff out.\""
"I realize how hypocritical that is, especially considering that I'm hiding what the parents had just told me."
"Cassius lets out a skeptical huff."
show cas annoyed with dis
c "\"You, help me?\""
m "\"Yes.\""
show cas right with dis
"Cassius seems to contemplate, then shakes his head."
c "\"Well, nothing there could help us. They simply torment me when I try to communicate with them.\""
m "\"Torment?\""
show cas righteyes with dis
c "\"They appear as demons and taunt me. It seems that the parents truly do want to cut off contact with us...which I'm fine with.\""
"Cassius says that last bit with such meek defiance that I almost feel sorry for him."
m "\"Maybe it was just the drug? I've heard plenty of stories of people freaking out on mind-altering stuff, especially if they have problems with anxiety—\""
show cas annoyed with dis
c "\"I do not have a weak mind, [mc].\""
m "\"Th—that doesn't mean you have a weak mind, sometimes you just—\""
show cas with dis
c "\"Enough. I will not have you speculating about my mental capacities.\""
"This time I'm the one sighing, wondering for the hundredth time how the hell this wolf is Amicus's brother."
m "\"So they didn't say anything to you?\""
"Cassius pauses, a frown tugging at the corners of his mouth."
show cas sad with dis
c "\"No.\""
"I raise an eyebrow at him."
show cas annoyed with dis
c "\"What? Of course they said things to me, but nothing useful.\""
m "\"You sure?\""
show cas angry with dis
c "\"Of course I'm sure! The parents have turned on us. That's all that I need to know.\""
show cas disappointed with dis
"I think back to the conversation we'd had in the hallucination."
"The monitor had told both of us that Cassius isn't the emperor, and if Cassius had heard what I heard, then that's probably what he's thinking about right now."
"But I know now isn't the time to challenge him, and I can tell that he's still trying to recover from the trip."
"Still, looking at him right now, staring at the ground, looking disheveled and defeated...I feel myself wanting to help him."
"Out of everyone on this moon, he seems to be the most stressed out, and I feel bad for him despite everything that's happened."
stop music fadeout 5.0
"But I know he doesn't want my pity right now."
"So, I eventually leave Cassius alone on the bed and wander back out into the halls, feeling as if weeks had past since I'd last been out here."
scene bg palace1 with dissolve
play loop "sfx/birds.ogg" fadein 3.0
"I think back to what that dragon-like creature had told me, about how I'm here for a reason, that this has all been planned out."
"Planned out by parents who seem to be completely frustrated at the behavior of the wolves and their inability to follow through on their \"plans\"."
"For a brief moment, I wonder how much more smoothly things would have gone if I'd been abducted by someone like Neferu and taken to somewhere like Khemia."
"But then I wouldn't have met Amicus."
"Besides, it seems like it's just the wolves that are giving the parents problems, not the other siblings."
"Which reminds me of the only bit of advice that the parents had given me; \"watch the cat\"."
"Spy on Alexios."
"That's something that I think I can do, if I'm careful."
"Despite the new level of scrutiny I've fallen under, I've also been walking around the halls of the palace for the past few days without incidence."
"I've even come across Cato a few times, but for whatever reason, he's completely ignored me."
"All for the better."
"So, I start to scour the palace for the cat."
"He's actually pretty hard to find when he's not looking for you, but I at least know that he's usually in the gardens, if not in the hallways watering the plants."
"So after eating a quick lunch, I decide to start my search in the gardens."
scene bg garden2 with dissolve
"I look back and forth through the foliage as I walk quietly along the various pathways."
"It's quiet, pleasant, and peaceful, but after everything that's happened, it has an ominous edge to it, like something could jump out at me at any moment."
"I do this for about half-an-hour before I start to realize how fruitless this search might be."
"Alex would be hard to find even if he {i}was{/i} out here, and besides, he could even be all the way out in the city doing his \"ambassador work\", whatever that is."
"Just as I'm about to give up though, I hear something."
"Sniffling, gasping, and...crying?"
stop loop fadeout 5.0
"I pause, listening."
"It's a bit difficult to hear through the slight rustling of leaves in the wind, but there's definitely someone out here that sounds upset."
"I can't really tell who it might be since it sounds like they're trying to keep quiet."
"That, and there's another sound too; another voice, and this one I recognize."
"Alex."
"It's a soft murmuring sound, like he's soothing someone, probably the person who's crying."
"I wait there a few moments, waiting to see if the sound fades or gets closer which would tell me if they're moving, but it stays constant."
"So, convinced that they're sitting down, or at least standing in the same spot, I creep closer to where the sound is coming from."
"It's in a secluded part of the garden, coming from a small square that's surrounded by trees and bushes."
"I'm familiar with this square, the one with the statue of Drusus, where I'd been laid out to die."
"I know that I can't use the little path that leads to the statue; I'd be seen for sure, so I walk up to the bushes that surround it and start looking for a break in the various branches and leaves."
"The sobbing sound continues, and I can hear Alex's voice more clearly now."
"I still can't quite tell exactly what he's saying, but I catch the occasional \"don't worry\" and, \"all is well\"."
"I can't imagine what's happening in there."
"I start to wonder if this is exactly what the parents had hoped I would come across, and my heart starts to hammer in my chest."
"Am I about to find something that's going to help me out of the mess we're in?"
"I finally find a thinner coverage in the foliage and I'm able to see through."
play music "music/romance.ogg" fadein 10.0
"First, I see Alex, his back to me, crouched on the ground in front of the statue."
"He's draped over something...someone, hugging them, his face pressed to the side of their head."
"I can only see their ears and parts of their shoulder, but I know right away that it's Cassius."
"He's got his head bowed deeply toward the ground, his paws to his face, shaking with his sobs."
"Alex hugs him tightly, whispering into his ear, clearly trying to comfort him."
"Cassius only responds with an occasional shake of his head before finally blurting out;"
c "\"But am I a fraud?\""
"His voice squeaks uncharacteristically on the last word and Alex responds with a gentle \"shh\" before nuzzling the wolf's muzzle."
"I watch for a few more moments before drawing back, feeling uncomfortable, knowing that this is a private moment between the two of them."
"I know now that this won't exactly help me in any way aside from making me feel even worse for Cassius."
"Still, I've found Alex, so I move away, toward a bench that's further up the path, one that gives me a good view of the entrance to the square and at a distance that won't make me seem suspicious."
"A good ten minutes pass before there's any movement."
stop music fadeout 10.0
play loop "sfx/birds.ogg" fadein 5.0
"First, Cassius comes out, in the process of straightening out his armor, his expression blank as he stalks off up the path, away from me."
"I wait a while...a good while, maybe another five minutes, wondering if Alex somehow took a different exit from the square."
"But at that moment, I see him walk out, looking completely neutral as he looks around."
"I freeze up, positive that he's about to see me even though that would be okay, but he instead walks straight ahead, toward the pond."
"I watch him go for a while, then follow."
"It feels strange trying to spy on the pet ambassador like this, especially when I have no idea what I'm doing."
"But this is the only hint I was given to free Amicus, and if this is the only way, then I'm going to do it."
scene bg garden1 with dissolve
stop loop fadeout 3.0
play music "sfx/fountain.ogg" fadein 3.0
"I find the cat at the pillars, already pulling away at the weeds."
"I sigh and wait, watching for a while, realizing that this could last hours since Alex always seemed to enjoy weeding for some reason."
"The cat is so meticulous about gardening here, and I have to wonder why considering his efforts really wouldn't be all that visible in a garden this big."
"But I remind myself of why I'm here and settle down on another bench, one that's also a good distance away so that I won't seem too suspicious if he sees me."
stop music fadeout 5.0
"This time, I sit there for a few hours, occasionally adjusting the way I'm seated as my ass gets sore on the stone bench, and as the sun sets, I realize how boring spying actually is."
scene bg garden2night with fade
play loop "sfx/crickets.ogg" fadein 3.0
"Around the second hour, the sun has completely set, and I debate just giving up and trying another day."
"At that moment, a drone suddenly drifts up to me, making me jump and duck my head down a little bit, as if that will help hide me from Alex."
com "\"Neferu requests—\""
m "\"Shh!\""
"I hiss at the drone, and Com's voice automatically dips into a whisper and goes on as if nothing had happened."
com "\"—your location and if you need his assistance.\""
"Of course, at that exact moment, I see Alex strolling up the path, though he doesn't move toward the palace."
"Instead, he starts walking up the path in my direction and I quickly stumble off the bench and into the bushes, praying that he didn't see me as I hide myself amongst the leaves."
"The drone follows me, then pauses at the edge of the sidewalk."
"I'm reminded that these things probably can't move off of the grid of the pathways."
"Just through the leaves, I can see the damn thing's lights on, stubbornly waiting for my answer."
"At the same time, I hear the soft scraping of Alex's sandals on the pathway as he moves closer."
"Damn it."
"It would have been better if I'd just stayed on the bench."
"Now this drone is gonna reveal me to Alex while I'm hiding in the bushes like the most suspicious person in the palace."
"I see the green tips of the cat's ears poke above the bushes as he hums softly."
"I crouch lower in the foliage until I can't even see that."
"I will the cat to just ignore the drone, but the humming stops and so do his footsteps, and I know that he's spotted it."
al "\"Hmm, do you have a stray drone out here, Com?\""
com "\"All drone machinery are accounted for, Alexios.\""
al "\"What's this one doing?\""
"I feel my heart stop, swallowing hard."
"There's a pause, as if Com is calculating something."
com "\"That information is classified, Alex.\""
al "\"By whom?\""
com "\"Neferu.\""
"There's a pause, then a chuckle as Alex's footsteps pick up again, moving further away to my left."
al "\"Oh, that jackal.\""
"I'm still holding my breath as I listen to the footsteps fade up the path before slowly rising up from my crouch, glaring at the drone."
m "\"Tell Neferu that I'm busy, but that I'll be back tonight. I have some things to tell him.\""
com "\"Message received. Thank you [mc].\""
m "\"Yeah, no problem.\""
"I say it sarcastically as the drone floats off in its slow, lazy way."
"At this point, the sun has set completely, and I have to wonder why Alexios has headed in that particular direction, leading either toward the gates of the palace, or the lake."
"I follow the path slowly, keeping my eyes peeled for the cat."
"At first, I'm almost positive that he would be heading for the gate, maybe on his way to the city."
"This would be the end of my little mission since I know I can't leave the boundaries of the palace without being...hurt somehow, probably killed."
scene bg lakenight with dissolve
"But instead, I spot the cat's form, just barely visible in front of the lake, its surface glinting from the light of the moon."
"I stop and hide behind a tree, making sure that I'm not close to any of the lamp posts."
"I watch as Alex moves around under the little gazebo with the watercrafts under it."
"Sure enough, a few minutes later, he comes gliding out on the Sightseer."
"He floats over the shore, then out onto the lake...in the direction of the island."
"I know right away that I'm seeing something important."
"There's nothing on the island for the cat to take care of, as far as I know, and unless he's going out there for a nighttime outing on the beach (extremely doubtful), then he's definitely doing something suspicious."
"I wait for a while, watching as the dark form of the cat and the craft get smaller and smaller until they basically disappear, out in the direction of the island."
stop loop fadeout 5.0
"Of course, I know I can't follow him out there right now, but I can definitely tell Neferu about it..."

scene bg emperorbedroomnight with fade
"Neferu is in his room when I arrive, tapping away at what looks like a transparent tablet."
"It's an odd thing to see considering the non-existence of portable technology in this palace."
"Maybe it's a Khemian thing."
"As soon as he sees me though, the display slides back into into the small metal bar that it had been projecting out of as he turns to face me."
play music "music/memories.ogg" fadein 3.0
show nef at center with dissolve
n "\"Hello, [mc]. You were gone for quite a while.\""
m "\"Uh, yeah.\""
show nef a with dis
n "\"Care to share how your visit went with Cassius and, hopefully, Amicus?\""
"It takes me a moment to remember exactly what he's talking about."
"After my little trip, everything that happened before it seems so distant."
"I try to tell Neferu as much as I remember involving Cassius before the parent thing, and he seems impressed."
show nef talking f with dis
n "\"Hm, I suppose bringing Cassius to our side won't be as difficult as I had previously thought. It seems he has similar misgivings about Cato.\""
m "\"Yeah, and Amicus is doing okay, just a bit depressed about everything that's happening, obviously.\""
"I pause then, which Neferu notices."
show nef serious with dis
n "\"Is there something else that happened?\""
"I take a deep breath, thinking how best to describe what I went through."
m "\"Well, when I was coming back, there was this weird smell coming from the meditation room...\""
show nef skeptic f with dis
"Neferu raises an eyebrow and I go on to explain how I'd ran into Cassius again, then everything that happened afterwards."
"When I finish, the jackal is quiet, just watching me with a narrowed gaze."
"This is usually the look he gives me when he's thinking hard about something, so I give him some time to respond."
"When he does, it's hesitant and reserved, not usually something I hear from Neferu."
show nef unsure f with dis
n "\"So it was a drug-induced hallucination, yes?\""
m "\"Well, I guess so, but I think it was real too. Like, Cassius was there, and he remembers seeing me with him.\""
n "\"Hmm...\""
m "\"What's wrong?\""
show nef serious with dis
n "\"Well, that is a very...primitive way to contact the parents. To put it bluntly, it does not work. It was a method used in the early days, during First Contact between sibling and parent.\""
n "\"They visited multiple times and in between visits some siblings, especially the wolves, would try to contact them again via psychotropic drug use. This could occasionally bring visions of higher beings, though they were not the parents, of course—\""
n "\"—simply imagined beings conjured up by a chemically-imbalanced brain.\""
n "\"This is likely what you experienced.\""
show nef unsure f with dis
n "\"To truly contact the parents you must do it through parental tech; complicated machinery that is able to transcend dimensions.\""
n "\"It is usually only usable by a single person, such as the emperor for the wolves or the pharaoh for my people.\""
"Neferu stops talking at this point, allowing me to take all that information in."
"So maybe I had imagined it all...even if it had seemed so real."
m "\"They told me they had a plan for me and everything.\""
show nef talking with dis
n "\"Often times such drugs stroke the ego of the user. They make you feel as if you are at the center of the universe, as if you are important...not saying that you aren't.\""
m "\"Have you tried it before?\""
show nef smile eyes a with dis
n "\"I've had brushes with such substances in my youth. Good for experiencing the fragility of reality and how we perceive it...but little else.\""
m "\"I see.\""
show nef with dis
n "\"Still, it sounds like you caught Cassius in a moment of vulnerability. He could trust you more because of it, if you treated the situation delicately.\""
m "\"Eh, maybe.\""
"I think back to when I saw him crying in front of the statue, but I don't want to tell Neferu about that, not really feeling it would be all that useful...or appropriate to share."
"But this reminds me of what else the \"parents\" had said to me."
m "\"Well, they also told me something else; to watch Alex.\""
show nef talking f with dis
n "\"Did they now?\""
m "\"Yeah, and I did. He's been acting weird ever since I got here, so I spied on him today and he sailed off to the island in the middle of the lake just now.\""
show nef with dis
"Neferu's got a strange, knowing smile on his face."
m "\"What?\""
n "\"I just find it interesting that you have similar suspicions of Alex that I did.\""
m "\"What do you mean?\""
n "\"I've been studying the cat myself and noticed a few odd things as well, including his trips to the island.\""
"I frown."
m "\"What? And you didn't tell me?\""
show nef talking f
n "\"Well, this rather desperate situation we're in only came about very recently, and I had little use for this information until now.\""
m "\"Well, what do you think he's doing?\""
"Neferu shrugs."
show nef a with dis
n "\"I don't know as I've not yet followed him to the island. You can imagine that I'm planning to now that we could use Alex on our side as well.\""
m "\"Turn everyone against Cato?\""
show nef with dis
n "\"Yes.\""
m "\"So if he's doing something...bad, then we would use it as blackmail?\""
n "\"Essentially. He is the closest person to Cassius and could possibly grant us access to classified information.\""
"I sigh, growing weary of all this backstabbing."
m "\"If it's the only way to help Amicus, I guess.\""
n "\"Oh, there are many ways, and I have a last resort plan in place.\""
"I wait, but Neferu doesn't go on."
m "\"Which is?\""
show nef serious with dis
n "\"Well, considering Amicus's birthright, he still has the ability to challenge whoever is on the throne, but—\""
m "\"Really?\""
"All this time Amicus could have just challenged Cassius again?"
"Then I realize that Neferu was about to go on."
m "\"But what?\""
n "\"A fight to the death, since the wolves love their violence, though the emperor would have to accept the challenge.\""
"The thought of that instantly makes me feel sick."
m "\"No way.\""
n "\"Again, last resort. I doubt Amicus would challenge his own brother, and I doubt Cassius would accept...at least at the moment.\""
"I can't even begin to contemplate a situation like that, and Neferu quickly changes the subject."
show nef with dis
n "\"Anyway, I should be off. I'd like to catch Alex in the act and based on previous observations I've made, I have another hour to do so.\""
"I blink in surprise."
m "\"Right now? Shouldn't we wait until like...tomorrow night?\""
n "\"He only goes once a week. Considering how urgent our situation is, I should get this done now.\""
m "\"Can I go too?\""
show nef serious with dis
n "\"[mc], remember what I said about needing to keep you safe?\""
m "\"Yeah, and it's Alex. What's he gonna do?\""
n "\"We should be prepared for anything.\""
m "\"Well, I think it's better if we both go, in case something {i}does{/i} happen and you need my help.\""
"Neferu lets out a soft sigh."
show nef sad a with dis
n "\"Alright.\""
"I'm surprised by how quickly he gives in."
n "\"I suppose you deserve to be treated as an equal in these plans we're making.\""
show nef angry with dis
n "\"Though if Amicus finds out I'm bringing you on these missions he'll have my hide.\""
m "\"I'll let him know I wanted to be part of it.\""
n "\"Mhm, as if that will convince him. Anyway, let's be off.\""
m "\"Okay.\""
hide nef with dissolve
"My excitement picks up as I get to my feet and follow Neferu to the door."
stop music fadeout 5.0
n "\"If we run into anyone, especially Cato, we simply tell them we're out for an evening stroll, understood?\""
m "\"Yep!\""
"Despite the potentially dangerous situation we're going into, my mood is lifted knowing that things are finally moving again."

scene bg lakenight with fade
play music "sfx/lakesounds.ogg" fadein 5.0
"Luckily, there's another Sightseer craft in the gazebo, though it looks much older and the floor on this one isn't transparent, which I'm fine with."
"I'd rather not gaze into the inky-blackness of the water beneath my feet while sailing to the island."
"Neferu is quiet most of the time, looking confident in everything he does as he prepares the craft."
"Finally, he reaches out his paw to chivalrously pull me on board."
"The lake laps quietly around us as we approach the island; a black mass amongst the ripples of reflected moonlight in the waves."
"I immediately spot Alex's craft sitting on the beach near where we'd had our little picnic all those weeks ago."
"We travel a little further up the shore, out of sight of the craft before we drift onto the beach."
scene bg islandnight with dissolve
"Neferu holds out a paw again to help me down, even though I don't need it."
"As I settle on the sand though, he leans in close to whisper in my ear."
show nef with dissolve
n "\"Wait here. Unfortunately, I believe simian footfalls are louder than that of a jackal.\""
m "\"Okay...but call me if something happens, or you need help.\""
show nef smile eyes with dis
"I see a smile on Neferu's face, and though it's amused, it's not in a condescending way at all."
n "\"Of course, my friend.\""
hide nef with dissolve
"And with that, the jackal disappears into the night, leaving me with only the little craft and the gentle sounds of the waves to keep me company."
"I don't have to wait long before I hear voices coming from further up the beach, and I know right away that it's Neferu and Alex."
"I wait for a few moments to see if Neferu will call my name."
"When he doesn't, I frown and look around before quietly making my way toward the voices."
"It's not like I expect he needs my help, but I don't want to miss anything important, and I feel like the moment of confrontation with Alex should involve me."
"As I get closer, I'm able to make out the words, and I see that the two of them are right on the edge of the woods, standing just a few feet apart."
"I crouch and hide along the tree line as I listen more closely to what they're saying."
show nef at right with dissolve
n "\"—beautiful night. I've always wanted to come to the island to gaze at the moon and planet, away from the lights of the palace.\""
show ale at left with dissolve
al "\"Ohh, I see. It is incredibly beautiful here, isn't it?\""
"While he's speaking in his typical, pleasant tone, I can definitely tell that Alex seems a bit nervous, his voice tight and a bit out of breath."
show nef unsure f with dis
n "\"So...\""
show ale sad e with dis
al "\"Yes?\""
"Alex looks around nervously."
show nef talking f with dis
n "\"I heard you speaking just before I happened upon you. Is there someone else with you?\""
show ale shocked e with dis
al "\"Me? Oh no, definitely not! You know, it's rather embarrassing, but sometimes I just talk to myself.\""
show nef smile eyes with dis
n "\"Don't be embarrassed, it's something I do as well.\""
show ale smile with dis
al "\"O—oh, I see.\""
"Alex seems to be relaxing a bit under Neferu's treatment, but tenses up again at the next sentence."
show nef smile with dis
n "\"Though I usually don't whisper to trees. Now THAT is a bit odd.\""
show ale flustered e with dis
al "\"...\""
"I see Alex's ears flatten, though I'm a bit confused at the statement."
"Whispering to trees?"
al "\"I—I...\""
"Alex doesn't seem to have an answer ready and stutters in the most guilty way imaginable."
"Weirdly enough though, he sidles up closer to Neferu."
show ale sad at center with moveinright
show nef with dis
al "\"N—Neferu, you're the one that's acting a bit odd right now, you know.\""
"The small cat's demeanor suddenly changes to a more...sultry approach, relaxing his shoulders and drifting a paw down his body."
"It doesn't seem natural at all though, unlike Neferu's smile as he stares down at the approaching cat."
"He's still smiling when Alex reaches up to cup his cheeks and kiss him right on the lips."
"I blink, surprised at the sudden turn this scenario has taken."
"Neferu looks anything but surprised though, grinning throughout the kiss as Alex tries to kiss deeper."
"Finally, the cat seems to notice the lack of response from the jackal and he draws back, frowning."
show ale serious e at left with moveinleft
"Neferu shakes his head."
show nef talking with dis
n "\"Oh Alex, you know that's my technique. It will not work on me. Now why don't we have a look at that tree?\""
show ale shocked e with dis
"Alex freezes up, looking around, and that's when I think he spots me."
stop music fadeout 5.0
al "\"Who—who's that?\""
play loop "music/tensebackground.ogg" fadein 3.0
"Neferu turns his head just slightly in my direction, and that's when Alex makes his move."
hide ale
hide nef
with dissolve
"He sends a kick sailing between the jackal's legs, and just as I'm readying myself to intervene, Neferu's paw is there, solidly stopping the attack."
"There's a pause, Neferu holding Alex's leg, forcing him to balance on one foot as the jackal's smile turns smug."
n "\"What a pity that you're not the first to try such a move on me. I've learned people on this moon fight dirty.\""
"Alex squeaks, but balls up a fist anyway, sending a straight punch square into Neferu's stomach."
play sound "sfx/thud.ogg"
"It connects with a hollow thud, bouncing off the jackal's abs like they're made of bricks, Neferu only grunting slightly in response."
n "\"Oof! Now that's a bit more like it!\""
play sound "sfx/thud5.ogg"
with vpunch
"Suddenly, Neferu uses a leg to sweep Alex's only foot off the ground, sending the cat onto his back in the sand."
"Neferu follows him down, pinning the cat there, almost engulfing Alex with his much bigger body."
show ale vshocked e at left with dissolve
al "\"Ah! Get—get off me! Help!\""
stop loop fadeout 5.0
"Alex spots me as I come out into the open, standing next to the two of them."
al "\"[mc]! Help me! The jackal's gone mad!\""
"I fold my arms and stand over him, and Alex quickly realizes that I'm definitely not here to help him."
show ale angry e with dis
al "\"What are you two doing!? I told you I know nothing [mc], why must you keep attacking me like this!?\""
"Alex continues to struggle meekly under the jackal, not even looking like he's trying to escape."
show nef talking f with dis
n "\"Attack {i}you{/i}? Then why is it {i}my{/i} stomach that is sore?\"" 
"Alex doesn't seem to be listening and tears start brimming in his eyes as he begins to sob."
"Now I'm fully convinced that his sobs in the bathing room were all an act."
show nef with dis
n "\"[mc].\""
"I turn my attention back to Neferu who's still smiling as always."
n "\"About ten paces directly in front of me is a large tree, larger than the others that surround it. Do you see it?\""
"I look ahead and immediately see what Neferu's talking about, the tree noticeably larger than the others, its branches stretching dozens of feet into the air, the leaves looking like silver in the moonlight."
m "\"Yes.\""
n "\"Go up to it, circle it, see if you can find a hollow.\""
"I do as I'm told, feeling a little apprehensive as I step just inside the dark woods."
show ale embarrassed e with dis
al "\"Wait...Neferu, [mc], I don't understand...why are you doing this?\""
"I realize at that moment how much I'm trusting Neferu here."
"I have no idea what's happening at all."
"The trunk of the tree is thick, enough that I wouldn't be able to touch hands if I were to hug it."
"I start looking for the hollow Neferu described, and as I walk around the tree, I immediately spot one on the other side of it."
"I look into the black hole, feeling a bit nervous at what I might find in there."
m "\"I foun—\""
play music "music/tension.ogg" fadein 3.0
"I stop as a tiny, red light in the hollow flares to life with my voice before fading again."
m "\"What the...\""
"It happens again, pulsing to the sound of my voice."
show nef talking with dis
n "\"You found it?\""
m "\"Yeah, and there's a little red light in there that's lighting up with my voice.\""
"I watch the hypnotic ebb and flow of the light as I speak."
show nef talking f with dis
n "\"Thank you, [mc], you may come back now.\""
"Gratefully, I return to the side of my Khemian friend, noticing that Alex's demeanor has completely changed now."
show ale serious with dis
"He's sullen, though almost expressionless as he lays under the jackal, not even pretending to be trying to escape at this point."
show nef with dis
n "\"Well...that settles it, doesn't it, Alex?\""
"Alex remains silent, staring up at the sky."
m "\"What is it?\""
"Neferu looks up at me."
show nef a with dis
n "\"Classic Omorfan-parent tech. They often combine plant life and machinery to create their gadgets. Rather ingenious, and they've recently been sharing their knowledge with us on Khemia.\""
al "\"What a mistake that was.\""
m "\"Wait, but what is it?\""
n "\"A communication device; it uses the branches as a massive antenna, capable of transmitting information great distances, though it's likely transmitting to Adastra City.\""
show nef unsure f with dis
n "\"There is likely a second spy there who then beams the information through a much more powerful machine...straight to Omorfa.\""
show nef smile a with dis
"Neferu grins in Alex's face."
n "\"Isn't that right, Alex?\""
"Once again, Alex remains silent, seeming to have shut down."
show nef with dis
n "\"So, do you want to be the one to tell Cassius, [mc]?\""
show ale embarrassed with dis
"That finally gets a reaction out of Alex, and he stiffens up, fur bristling out as he snarls at Neferu."
al "\"And for what reason, jackal? We're all spies here, including you...{i}especially{/i} you.\""
show nef smile eyes a with dis
n "\"Oh? I have no idea what you're talking about, Alex.\""
"Neferu's tone says otherwise."
"Alex continues to glare up at the jackal, his fur starting to lay flat again."
show ale serious with dis
al "\"Oh, you think I'm that stupid? You think I just let you fuck me without any regard to your intentions, without studying you? I know why you're here, jackal.\""
show nef with dis
n "\"Do enlighten me, {i}cat{/i}.\""
al "\"You're floundering here, looking to make a name for yourself. The Pharaoh practically tossed you off the planet to attempt to cultivate a hopeless alliance on Adastra.\""
show nef serious with dis
"Neferu's eyes narrow."
al "\"How unfulfilling it must be to be the second-born; unable to escape the shadow of your brother, unable to make father proud, stuck on this moon getting your balls kicked in by the bigot wolves.\""
"Alex sounds and looks almost unrecognizable."
al "\"Even your sisters; the third and fourth-born, have secured positions of greater prestige than you.\""
show nef angry with dis
"I see Neferu grip tighter into Alex, but the cat goes on."
al "\"In an era when the royal family has already given up so much power, you're desperate behind that facade of confidence, terrified of withering away into historical insignificance.\""
al "\"You'll be less than a footnote in the Khemian history books.\""
"Neferu isn't smiling anymore, and I can tell that he's been caught off-guard just as much as me by the cat's complete change in character."
"Still, he keeps his hold on the cat, remarking coolly:"
n "\"I would choose my words more carefully if I were you, considering your position right now. As I was saying, we'll be reporting this to the emperor as soon as we return to the palace.\""
"Alex seems to deflate again, apparently satisfied with the hits he'd gotten in on the jackal."
al "\"What do you want?\""
show nef serious with dis
n "\"Hm?\""
al "\"Don't play stupid, what do you want from me? You've known I was a spy since you first got here and you're only doing this now because you want something.\""
show nef a with dis
stop music fadeout 10.0
play loop "sfx/lakesounds.ogg" fadein 10.0
n "\"Oh, how considerate of you, well...\""
"Neferu looks up at me."
show nef sidesmile f with dis
n "\"What do you think we want, [mc]?\""
m "\"Full access to the archives.\""
"Alex snorts."
al "\"I don't have that.\""
show nef skeptic f with dis
n "\"Then get it. We know how close you are to Cassius. Make something up as to why you need it, then grant us access.\""
al "\"For what reason?\""
n "\"To help Amicus. Cassius will not be harmed by this. You have until next week, otherwise the emperor will know of your treason.\""
"Alex remains quiet, and Neferu seems satisfied with that, pushing off the cat and getting to his feet."
show nef serious with dis
n "\"Let us be off.\""
"The jackal speaks briskly to me before turning on his heel and making his way back to the craft."
hide nef with dissolve
"I look down at Alex, watching as the cat simply stares at the moons, not even acknowledging me."

scene bg lakenight with dissolve
"The way back is a bit awkward, Neferu quiet, clearly upset."
"I haven't really ever seen him like this before, and I have to remind myself that I probably rarely see the real Neferu."
"He's putting on an act just like Alex, just like they both have to."
"And though I'm curious about his family situation, I have enough sense not to pry."
"Instead, I ask what I'm most worried about:"
m "\"What's to stop Alex from betraying us? He could just as easily tell Cassius about our plot.\""
"The jackal is staring off into the water, his elbows on the railing of the Sightseer as he hunches over."
n "\"He won't. He can't bear the thought of  Cassius knowing of his betrayal.\""
"The usual confidence and natural smugness that's usually in the jackal's voice is completely missing, his tone flat."
m "\"You sure?\""
stop loop fadeout 5.0
n "\"Yes. His love for Cassius is almost equal to that of his loyalty to Omorfa, which is why I assured him that Cassius wouldn't be harmed by our plans. We have little to worry about.\""
"The jackal's mood puts me off from asking any more questions, and we sail the rest of the way to the palace in silence."

scene bg palace1night with transition_fade
play loop "sfx/crickets.ogg" fadein 3.0
"Three days later, Alex is able to gain full access to the archives."
"He doesn't explain to us how he did it, instead simply notifying Neferu of the specific time he'd open the archives for us and to be ready."
"I don't have to argue to come along this time, instead Virginia tells me that I'll need to go if we're to erase my profile from the palace's database."
"Doing this will allow me to leave the palace without being killed by Com; just another last resort in case things go bad."
"Neferu stays behind this time, deciding it to be best considering he's not exactly needed for what we're about to do."
show ale serious with dissolve
"Alex walks stiffly ahead of us, not speaking or really acknowledging us in any way."
"I find it unnerving after knowing the cat for so long, though Virginia doesn't seem bothered at all."
"We walk to a portion of the palace that I haven't been to very often, mostly because I was never shown the area."
stop loop fadeout 3.0
"Alex comes to a door that he presses his hand to, and unlike the other black panels, this one flashes a green color before the door opens."
scene bg archivesnight with dissolve
play sound "sfx/dooropen.ogg"
play loop "sfx/archives.ogg" fadein 3.0
"We walk inside the room, and I get my first look at the archive."
"I guess I'd expected rows of bookshelves, full of some type of digital storage, or whatever the wolves might use."
"Instead, I'm greeted by the sight of a giant, blue, glowing, sphere, with a honeycomb pattern covering its surface."
"What's most striking about it though is the swirling characters that appear and disappear just over the surface."
"They're symbols I don't recognize, not any that I've seen on Adastra before."
"Sitting in front of the floating sphere are two stone dragons, mouths open in silent snarls."
show ale serious with dissolve
"Alex seems to be in a hurry as he walks up to the globe."
"Without hesitation, he sticks his paw into the swirling blue and the characters and swirls seem to congregate around it before the whole thing pulses."
"This seems to satisfy the cat as he turns away."
al "\"That should give you full access. You're on your own from here.\""
hide ale with dissolve
"With that, the cat leaves."
"I watch him disappear out the door, for the first time feeling a bit sad at how our relationship has changed."
"Virginia remains unbothered though, walking up to the blue sphere as I follow."
scene archives1 with slow_dissolve
"I stand there awkwardly for a moment before clearing my throat."
m "\"So what is this thing?\""
v "\"The archive.\""
m "\"Yeah, but it looks—\""
v "\"It's parental, yes, and no, I don't know how it works. It was also used as the method of communication with the parents before they ceased contact, hence the meditation pillow.\""
"Virginia gestures at the pillow before she leans forward slightly, a streak of blue light wrapping around her head briefly before she leans back."
show archives3 with dis
v "\"It connects to the host's brain, similar to the lingua and operates on mind-control.\""
m "\"Wow.\""
v "\"Yes, I haven't used it often, but it's fairly easy to control. You'll find out soon enough.\""
m "\"Oh.\""
"I feel a bit nervous, but Virginia focuses back on the blue globe."
scene archives1 with dis
"Suddenly, a small screen appears over the sphere, and I see what looks like the amphitheater."
v "\"Hmmm...what day was the final trial?\""
"I'm about to answer when suddenly Virginia just waves me into silence, focusing on the screen again."
"I see the scene change to a bloody sunset, and I feel the same anxiety I'd felt that day as I see Cato and Amicus appear on the screen, followed by me and Cassius."
"The angle is high, and the scene is a bit distant, probably from the palace, but I can make everyone out clearly."
"Cassius strips and hurries down the steps to the amphitheater, and I want to look away, but don't as Cato turns on Amicus and punches him in the face."
show archives2 with dis
"Virginia's reaction is small but noticeable, clearly surprised by Cato's brutality."
"What follows is the awkward, staged posing, and the pin."
"Then, the footage of me using the nervo on Cassius."
"This is followed by Amicus tearing off Cato's visor."
"After that, I run off-screen, and I get to watch as drones descend on Amicus and he suddenly goes limp as they, I assume, stun him."
"Virginia watches all of this with an open mouth until Amicus is escorted away and Cato is picked up by a small ship that lands in the middle of the amphitheater."
"Then she shakes her head."
v "\"Males...\""
"Virginia sighs out in frustration as the screen fades."
m "\"So you got the footage?\""
show archives4 with dis
v "\"I've filed it away to a domain accessible by both me and Neferu. We'll figure out a way to use it delicately.\""
m "\"And the investigation into the crash?\""
"This is something that I'd brought up to Virginia and Neferu before we came here, even though both seemed skeptical that it could be useful in any way."
"That even Cato wouldn't be so devious as to kill his own friend, a friend that happened to be the emperor."
show archives1 with dis
"Even now, Virginia sighs as if it's an annoying inconvenience, but focuses for a moment until she seems satisfied."
v "\"Done, all documents related to the investigation are now in the same location. We'll go over it later...well, at least you and Neferu can.\""
"There's a momentary pause."
m "\"Well, that was easy.\""
show archives4 with dis
v "\"What did you expect? Parental tech makes everything fast and easy.\""
m "\"Yeah, I suppose.\""
v "\"So...are you ready to use it?\""
m "\"I—I think so.\""
"Virginia smiles at me."
v "\"Don't worry, it's easy. Simply keep your mind clear of anything except your objective; your profile and how it should be wiped clean from the archive.\""
m "\"My profile...\""
"I try to think up how I should imagine a profile, but Virginia stops me."
v "\"You're already thinking too much. Just this; your profile, wipe it from the archives.\""
show archives1 with dis
"I swallow hard, but allow Virginia to gently push me forward until one of the tendrils touches my head."
"It's a cool feeling at first, then suddenly my body seize up involuntarily as it feels like my entire brain twitches."
v "\"Keep focused on your objective.\""
stop loop fadeout 5.0
"My profile, gone...my profile, erase it...my profile...delete from the archives..."

scene bg black with slow_dissolve
play music "music/between dimensions.ogg"
"A dagger, screams, pain, blood, hissing breath, spurting red, absolute anguish—"
a "\"[mc]! No, please! Don't leave me here! Please, come back to me! You can't leave me to be alone like this!\""
"Amicus screams right into my ear, and I've never heard him sound like this before."
"It's horrible, and I know I need to comfort him, to tell him I'm not leaving, but my voice is gone and air hisses from my throat."
a "\"No, no, no...speak to me!\""
"Amicus's voice rises in pitch, panicking, becoming desperate."
"Then it all stops."
"..."
mon "\"You can prevent this...\""
"..."
mon "\"But only if you submit yourself to the benevolent will of the parents..."
"..."
mon "\"Will you?\""

menu:
    "Yes":
        $ end_game1 += 1
        $ fate = True
        "..."
    "No":
        $ end_game3 += 1
        "..."

scene bg archivesnight
"I gasp and pull back, head reeling."
"I feel soft but strong paws grip me around the shoulders."
show vir serious with dissolve
v "\"Are you alright?\""
"I look around, wide-eyed, feeling almost sick as that weird feeling of control in brain suddenly leaves."
m "\"I—\""
"I don't know what to say, and Virginia glances back at the sphere."
v "\"Might not be suited to a simian brain. Com?\""
com "\"Yes Virginia?\""
v "\"Locate [mc]'s profile.\""
com "\"There is no such profile archived.\""
v "\"Well, you did it at least. Let's get you back to Neferu's room.\""
scene bg palace1night with dissolve
"We walk through the halls, Virginia having to help because of my unsteady feet."
"I'm stunned, feeling as if I'd just come up from another drug trip."
"But it's not what I felt, or even the visions of violence that have me shaken up."
"It's Amicus's screams of despair that linger in my head..."
"I have to see him as soon as possible."
"I have to make sure he's all right."
stop music fadeout 5.0

scene bg dungeons with transition_fade
show ami u with dissolve
a "\"Mmmh, you smell so good...\""
play music "music/dawn.ogg" fadein 3.0
"Amicus has me pinned to the floor on the little blanket that I brought with me."
"He's smothering me with his big body, grinding down against me as he licks and nips at my neck."
"I haven't even been here more than a minute."
m "\"W—wait, what if...what if Com sees...\""
"I gasp around the licks and Amicus responds by holding my head in his giant paws, keeping me steady as he starts to push his hips against me, his thighs forcing my legs upward."
"Amicus mumbles into my throat."
show ami eyes u with dis
a "\"Then let him watch.\""
"Com isn't watching, as far as I know."
"Somehow I'd been able to convince Cassius to give us more privacy."
"Actually, I think I'd just grossed him out when I'd asked, wrinkling his nose as he instructed Com to keep the drone at the top of the ladder this time."
"At that moment, I feel the wolf's hard length pressing at my ass, and even though I'm in my underwear and robes, I pull back."
m "\"Whoa, not now, Amicus!\""
"Amicus goes on nuzzling me, moving to my face and locking lips with me for several seconds while he continues to push his hips against me."
"He finally pulls back a little."
a "\"I know, I'm just playing around a little. I've been down here too long. I love you, everything about you.\""
m "\"Clearly.\""
"That's all I'm able to say before he starts to kiss me again, licking and sucking and I'm at least glad that it tastes like they're providing him with that mouthwash stuff down here."
"I've never seen Amicus so horny before, which is saying something, his paws gripping and stroking at me almost desperately as his muzzle kisses every inch of my neck and face."
"He pushes his body down against mine, his considerable chest and belly crushing me flat against the ground."
"But when his muzzle starts dipping down lower, snuffling against my chest and under my robes, I decide that I've had enough."
"I reach around to grab his upraised rear, getting a handful of thick, furry ass as my fingers squeeze dangerously close to the spot under his tail."
show ami surprised u with dis
"Predictably, Amicus gasps in surprise and pulls back, quickly sitting up so that his rear is safely pressed against the blanket and I have room to finally sit up myself."
show ami embarrassed u with dis
a "\"What was that for?\""
m "\"For not letting me catch my breath. And I know you don't like things near your butt.\""
show ami disappointed blush u with dis
a "\"Well, emperors shouldn't have things near their butt.\""
"I roll my eyes at his silly, but understandable insecurity, and crawl up to Amicus to sit in his lap, the wolf eagerly pulling me in."
show ami eyes u with dis
a "\"I love you.\""
m "\"I love you too.\""
"Amicus rubs his paws up and down my arms and shoulders, still just feeling me out."
a "\"I can't wait to get out of here. No more hiding when I'm emperor. I'm going to show you the real Adastra. Being stuck behind these walls is not how the emperor's beautiful lover should be treated.\""
"I touch back, pressing my hands over his paws and resting my head against his chest, listening to the rumble of his voice."
m "\"Oh? And what's the real Adastra?\""
"Amicus pulls his paw away for just a moment to wave it dismissively before returning it to press against my chest."
a "\"These politics...it doesn't represent the moon's true face. I need to take you to other cities and landscapes. The people are vastly different too, from region to region.\""
m "\"Mmmh.\""
"I listen to him contentedly for a few minutes, happy to just hear him speak again, reminded of how easy it is for us to just talk to each other."
"And we actually have time to talk."
"Cato is in a different city on official business, so Cassius had granted us at least a little more time than the last visit."
"Amicus rocks back and forth as I pet the fur on his chest, listening to his heartbeat."
"It's clear that they allow him to bathe down here, but the lack of any perfume leaves only the slight smell of his natural musk."
"While I miss the lavender smell I'm used to, I don't mind the masculine scent he's giving off, especially after our little reunion just now."
"I want to sit here forever, feeling completely calm and safe for the first time this week."
"I know it has to end though, and there's so much to tell the wolf, so I pull back, looking up at Amicus's face."
m "\"Amicus?\""
show ami u with dis
a "\"Yes?\""
m "\"I need to talk to you about something.\""
a "\"Go on.\""
"Amicus leans down, pressing his nose against my hair and inhaling deeply."
m "\"It's...about the parents, I think. I need to talk to you about something they showed me.\""

jump a3s1